// packages/bridge-ui/src/components/Dialogs/RetryDialog/RetryDialog.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { t } from 'svelte-i18n';
  import { type Hash, UserRejectedRequestError } from 'viem';

  import { chainConfig } from '$chainConfig';
  import { CloseButton } from '$components/Button';
  import { DesktopOrLarger } from '$components/DesktopOrLarger';
  import { DialogStep, DialogStepper } from '$components/Dialogs/Stepper';
  import {
    errorToast,
    infoToast,
    successToast,
    warningToast,
  } from '$components/NotificationToast/NotificationToast.svelte';
  import { OnAccount } from '$components/OnAccount';
  import type { BridgeTransaction } from '$libs/bridge';
  import { closeOnEscapeOrOutsideClick } from '$libs/customActions';
  import { getLogger } from '$libs/util/logger';
  import { pendingTransactions } from '$stores/pendingTransactions';

  import Claim from '../Claim.svelte';
  import { claimWithQuotaGuard, showQuotaToastForClaimError } from '../ClaimDialog/quota';
  import { ClaimConfirmStep, ReviewStep } from '../Shared';
  import ClaimPreCheck from '../Shared/ClaimPreCheck.svelte';
  import { ClaimAction } from '../Shared/types';
  import RetryStepNavigation from './RetryStepNavigation.svelte';
  import RetryOptionStep from './RetrySteps/RetryOptionStep.svelte';
  import { selectedRetryMethod } from './state';
  import { INITIAL_STEP, RETRY_OPTION, RetrySteps } from './types';

  export let dialogOpen = false;

  export let bridgeTx: BridgeTransaction;

  export let loading = false;

  export let activeStep: RetrySteps = INITIAL_STEP;

  const log = getLogger('RetryDialog');
  const dispatch = createEventDispatcher();

  const dialogId = `dialog-${crypto.randomUUID()}`;

  let canContinue = false;
  let retrying: boolean;
  let retryDone = false;
  let ClaimComponent: Claim;
  let isDesktopOrLarger = false;

  let hideContinueButton = false;

  let txHash: Hash;

  const showQuotaReachedToast = () => {
    errorToast({
      title: $t('bridge.errors.claim.quota_reached.title'),
      message: $t('bridge.errors.claim.quota_reached.message'),
    });
  };

  const logQuotaCheckError = (quotaError: unknown) => {
    console.error('Failed to check claim quota', quotaError);
  };

  const handleRetryError = async (event: CustomEvent<{ error: unknown }>) => {
    const err = event.detail.error;
    if (
      !(await showQuotaToastForClaimError(err, bridgeTx, {
        showQuotaReachedToast,
        onQuotaCheckError: logQuotaCheckError,
      }))
    ) {
      console.error(err);
      // Every non-quota failure needs user-visible feedback, not just a console line
      if (err instanceof UserRejectedRequestError) {
        warningToast({ title: $t('transactions.actions.claim.rejected.title') });
      } else {
        errorToast({ title: $t('bridge.errors.retry_error') });
      }
    }
    retrying = false;
  };

  const handleAccountChange = () => {
    reset();
  };

  const reset = () => {
    activeStep = INITIAL_STEP;
    $selectedRetryMethod = RETRY_OPTION.CONTINUE;
    retryDone = false;
    retrying = false;
  };

  const closeDialog = () => {
    dialogOpen = false;
    reset();
  };

  export const handleClaimClick = async () => {
    await claimWithQuotaGuard({
      bridgeTx,
      claim: () => ClaimComponent.claim(ClaimAction.RETRY),
      setClaiming: (value) => (retrying = value),
      showQuotaReachedToast,
      onQuotaCheckError: logQuotaCheckError,
    });
  };

  const handleRetryTxSent = async (event: CustomEvent<{ txHash: Hash }>) => {
    const { txHash: transactionHash } = event.detail;
    txHash = transactionHash;
    log('handle claim tx sent', txHash);
    retrying = true;

    const explorer = chainConfig[Number(bridgeTx.destChainId)]?.blockExplorers?.default.url;
    log('explorer', explorer);
    infoToast({
      title: $t('transactions.actions.claim.tx.title'),
      message: $t('transactions.actions.claim.tx.message', {
        values: {
          token: bridgeTx.symbol,
          url: `${explorer}/tx/${txHash}`,
        },
      }),
    });

    try {
      await pendingTransactions.add(txHash, Number(bridgeTx.destChainId));
    } catch (error) {
      // A reverted or timed-out retry must not leave the dialog spinning forever
      log('retry transaction failed or timed out', { txHash, error });
      retrying = false;
      errorToast({ title: $t('bridge.errors.retry_error') });
      return;
    }

    retrying = false;
    retryDone = true;

    dispatch('retryDone');

    successToast({
      title: $t('transactions.actions.claim.success.title'),
      message: $t('transactions.actions.claim.tx.message', {
        values: {
          url: `${explorer}/tx/${txHash}`,
        },
      }),
    });
  };
</script>

<dialog
  id={dialogId}
  class="modal {isDesktopOrLarger ? '' : 'modal-bottom'}"
  class:modal-open={dialogOpen}
  use:closeOnEscapeOrOutsideClick={{ enabled: dialogOpen, callback: closeDialog, uuid: dialogId }}>
  <div class="modal-box relative px-6 py-[35px] w-full bg-neutral-background absolute">
    <div class="w-full f-between-center">
      <CloseButton onClick={closeDialog} />
      <h3 class="title-body-bold">{$t('transactions.retry.steps.title')}</h3>
    </div>
    <div class="h-sep mx-[-24px] mt-[20px]" />

    <div class="w-full h-full f-col">
      <DialogStepper>
        <DialogStep
          stepIndex={RetrySteps.CHECK}
          currentStepIndex={activeStep}
          isActive={activeStep === RetrySteps.CHECK}>{$t('transactions.claim.steps.pre_check.title')}</DialogStep>
        <DialogStep
          stepIndex={RetrySteps.SELECT}
          currentStepIndex={activeStep}
          isActive={activeStep === RetrySteps.SELECT}>{$t('transactions.retry.steps.select.title')}</DialogStep>
        <DialogStep
          stepIndex={RetrySteps.REVIEW}
          currentStepIndex={activeStep}
          isActive={activeStep === RetrySteps.REVIEW}>{$t('common.review')}</DialogStep>
        <DialogStep
          stepIndex={RetrySteps.CONFIRM}
          currentStepIndex={activeStep}
          isActive={activeStep === RetrySteps.CONFIRM}>{$t('common.confirm')}</DialogStep>
      </DialogStepper>

      {#if activeStep === RetrySteps.CHECK}
        <ClaimPreCheck tx={bridgeTx} bind:canContinue bind:hideContinueButton on:closeDialog={closeDialog} />
      {:else if activeStep === RetrySteps.SELECT}
        <RetryOptionStep bind:canContinue />
      {:else if activeStep === RetrySteps.REVIEW}
        <ReviewStep bind:tx={bridgeTx} />
      {:else if activeStep === RetrySteps.CONFIRM}
        <ClaimConfirmStep
          {bridgeTx}
          bind:txHash
          on:claim={handleClaimClick}
          bind:claiming={retrying}
          bind:canClaim={canContinue}
          bind:claimingDone={retryDone} />
      {/if}
      <div class="f-col text-left self-end h-full w-full">
        <div class="f-col gap-4 mt-[20px]">
          <RetryStepNavigation
            bind:activeStep
            bind:canContinue
            bind:loading
            bind:retrying
            on:closeDialog={closeDialog}
            bind:retryDone />
        </div>
      </div>
    </div>
  </div>
  <button class="overlay-backdrop" data-modal-uuid={dialogId} />
</dialog>

<Claim bind:bridgeTx bind:this={ClaimComponent} on:error={handleRetryError} on:claimingTxSent={handleRetryTxSent} />

<OnAccount change={handleAccountChange} />

<DesktopOrLarger bind:is={isDesktopOrLarger} />

// packages/bridge-ui-next/src/components/Dialogs/RetryDialog/RetryDialog.tsx
"use client";

// React port of
// src/components/Dialogs/RetryDialog/RetryDialog.svelte.
//
// COMPONENT CONVENTION mapping:
//   - `export let dialogOpen` (two-way `bind:dialogOpen`) -> controlled
//     `dialogOpen` prop + `onDialogOpenChange(open)`. `closeDialog()` reports
//     `false` up (Svelte `dialogOpen = false`).
//   - `export let bridgeTx` -> prop.
//   - `export let loading` (bound, READ-only here) -> `loading` prop.
//   - `export let activeStep` (two-way `bind:activeStep`) -> controlled
//     `activeStep` prop + `onActiveStepChange`. The component also mutates it
//     internally (reset()/step navigation), so it is mirrored into local state
//     seeded from the prop and every change is reported up.
//   - `export const handleClaimClick` (PUBLIC method) -> exposed via
//     `useImperativeHandle` on a forwarded ref (`RetryDialogHandle`), AND wired
//     internally as the `onClaim` handler of `ClaimConfirmStep` (mirroring the
//     original `on:claim={handleClaimClick}`).
//   - `bind:this={ClaimComponent}` (calling `ClaimComponent.claim(...)`) -> a
//     ref to the shared `Claim` component exposing an imperative `claim()`
//     method (`ClaimHandle`). `Claim` is a sibling unit (Dialogs/Claim) and is
//     assumed to follow the COMPONENT CONVENTION + expose this handle.
//   - `createEventDispatcher` events:
//       dispatch('retryDone') -> onRetryDone()
//   - Child `bind:` props (canContinue, hideContinueButton, txHash, claiming
//     [`retrying`], retryDone) -> local state controlled into the children with
//     paired `onXChange` callbacks.
//   - `use:closeOnEscapeOrOutsideClick` -> useCloseOnEscapeOrOutsideClick hook.
//   - `<DesktopOrLarger bind:is={isDesktopOrLarger} />` -> useDesktopOrLarger().
//   - svelte-i18n `$t(key, { values })` -> react-i18next `t(key, { ... })`
//     (the `values` wrapper is dropped per the i18n migration).
//   - `$selectedRetryMethod = RETRY_OPTION.CONTINUE` -> selectedRetryMethod
//     vanilla store `.setState(...)` (imperative reset).
//   - `pendingTransactions.add(...)` -> imperative vanilla store add (preserved).
//
// DOM / class strings preserved verbatim for pixel parity.

import {
  forwardRef,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import type { Hash } from "viem";

import { chainConfig } from "$chainConfig";
import { CloseButton } from "@/components/Button";
import { useDesktopOrLarger } from "@/components/DesktopOrLarger";
import Claim, { type ClaimHandle } from "@/components/Dialogs/Claim";
import {
  errorToast,
  infoToast,
  successToast,
} from "@/components/NotificationToast";
import { OnAccount } from "@/components/OnAccount";
import type { BridgeTransaction } from "@/libs/bridge";
import { useCloseOnEscapeOrOutsideClick } from "@/libs/customActions";
import { getLogger } from "@/libs/util/logger";
import { useTranslation } from "@/i18n/useTranslation";
import { cn } from "@/lib/utils";
import { pendingTransactions } from "@/stores/pendingTransactions";

import {
  claimWithQuotaGuard,
  showQuotaToastForClaimError,
} from "../ClaimDialog/quota";
import ClaimConfirmStep from "../Shared/ClaimConfirmStep";
import ClaimPreCheck from "../Shared/ClaimPreCheck";
import ReviewStep from "../Shared/ReviewStep";
import { ClaimAction } from "../Shared/types";
import DialogStep from "../Stepper/DialogStep";
import DialogStepper from "../Stepper/DialogStepper";
import RetryStepNavigation from "./RetryStepNavigation";
import RetryOptionStep from "./RetrySteps/RetryOptionStep";
import { selectedRetryMethod } from "./state";
import { INITIAL_STEP, RETRY_OPTION, RetrySteps } from "./types";

const log = getLogger("RetryDialog");

export interface RetryDialogHandle {
  /** Public method (Svelte `export const handleClaimClick`). */
  handleClaimClick: () => Promise<void>;
}

export interface RetryDialogProps {
  /** Two-way `bind:dialogOpen`. */
  dialogOpen?: boolean;
  onDialogOpenChange?: (open: boolean) => void;

  bridgeTx: BridgeTransaction;

  loading?: boolean;

  /** Two-way `bind:activeStep`. */
  activeStep?: RetrySteps;
  onActiveStepChange?: (step: RetrySteps) => void;

  /** dispatch('retryDone'). */
  onRetryDone?: () => void;
}

const RetryDialog = forwardRef<RetryDialogHandle, RetryDialogProps>(
  function RetryDialog(
    {
      dialogOpen = false,
      onDialogOpenChange,
      bridgeTx,
      loading = false,
      activeStep: activeStepProp = INITIAL_STEP,
      onActiveStepChange,
      onRetryDone,
    },
    ref,
  ) {
    const { t } = useTranslation();

    // SSR-safe per-instance id (replaces Svelte `crypto.randomUUID()`).
    const dialogId = `dialog-${useId()}`;

    const isDesktopOrLarger = useDesktopOrLarger();

    // Two-way `bind:activeStep` mirrored into local state seeded from the prop.
    const [activeStep, setActiveStepState] =
      useState<RetrySteps>(activeStepProp);
    const setActiveStep = (step: RetrySteps) => {
      setActiveStepState(step);
      onActiveStepChange?.(step);
    };
    // Keep local in sync if the parent pushes a new controlled value.
    useEffect(() => {
      setActiveStepState(activeStepProp);
    }, [activeStepProp]);

    const [canContinue, setCanContinue] = useState(false);
    // let retrying: boolean;
    const [retrying, setRetrying] = useState<boolean>(false);
    const [retryDone, setRetryDone] = useState(false);
    const claimComponentRef = useRef<ClaimHandle>(null);
    const [hideContinueButton, setHideContinueButton] =
      useState<boolean>(false);
    // let txHash: Hash;
    const [txHash, setTxHash] = useState<Hash>();

    const showQuotaReachedToast = () => {
      errorToast({
        title: t("bridge.errors.claim.quota_reached.title"),
        message: t("bridge.errors.claim.quota_reached.message"),
      });
    };

    const logQuotaCheckError = (quotaError: unknown) => {
      console.error("Failed to check claim quota", quotaError);
    };

    const handleRetryError = async (detail: { error: unknown }) => {
      const err = detail.error;
      if (
        !(await showQuotaToastForClaimError(err, bridgeTx, {
          showQuotaReachedToast,
          onQuotaCheckError: logQuotaCheckError,
        }))
      ) {
        console.error(err);
      }
      setRetrying(false);
    };

    const reset = () => {
      setActiveStep(INITIAL_STEP);
      selectedRetryMethod.setState(RETRY_OPTION.CONTINUE);
      setRetryDone(false);
    };

    const handleAccountChange = () => {
      reset();
    };

    const closeDialog = () => {
      onDialogOpenChange?.(false);
      reset();
    };

    const handleClaimClick = async () => {
      await claimWithQuotaGuard({
        bridgeTx,
        claim: async () => {
          await claimComponentRef.current?.claim(ClaimAction.RETRY);
        },
        setClaiming: setRetrying,
        showQuotaReachedToast,
        onQuotaCheckError: logQuotaCheckError,
      });
    };

    // Expose the public method (Svelte `export const handleClaimClick`).
    useImperativeHandle(ref, () => ({ handleClaimClick }));

    // The shared `Claim` component dispatches `claimingTxSent` with `{ txHash, action }`
    // (see ClaimDialog's `handleClaimTxSent`). The source RetryDialog only reads
    // `txHash`, so `action` is accepted but ignored to stay compatible with the
    // assumed `Claim` handle's callback signature.
    const handleRetryTxSent = async (detail: {
      txHash: Hash;
      action: ClaimAction;
    }) => {
      const { txHash: transactionHash } = detail;
      setTxHash(transactionHash);
      log("handle claim tx sent", transactionHash);
      setRetrying(true);

      const explorer = (
        chainConfig as Record<
          number,
          { blockExplorers?: { default: { url: string } } }
        >
      )[Number(bridgeTx.destChainId)]?.blockExplorers?.default.url;
      log("explorer", explorer);
      infoToast({
        title: t("transactions.actions.claim.tx.title"),
        message: t("transactions.actions.claim.tx.message", {
          token: bridgeTx.symbol,
          url: `${explorer}/tx/${transactionHash}`,
        }),
      });
      await pendingTransactions.add(
        transactionHash,
        Number(bridgeTx.destChainId),
      );

      setRetryDone(true);

      onRetryDone?.();

      successToast({
        title: t("transactions.actions.claim.success.title"),
        // NOTE: the source reuses the `claim.tx.message` key here (not the
        // `success.message` key) and passes only `url` — preserved verbatim.
        message: t("transactions.actions.claim.tx.message", {
          url: `${explorer}/tx/${transactionHash}`,
        }),
      });
    };

    const dialogRef = useRef<HTMLDialogElement>(null);
    useCloseOnEscapeOrOutsideClick(dialogRef, {
      enabled: dialogOpen,
      callback: closeDialog,
      uuid: dialogId,
    });

    return (
      <>
        <dialog
          ref={dialogRef}
          id={dialogId}
          className={cn(
            "modal",
            isDesktopOrLarger ? "" : "modal-bottom",
            dialogOpen && "modal-open",
          )}
        >
          <div className="modal-box relative px-6 py-[35px] w-full bg-neutral-background absolute">
            <div className="w-full f-between-center">
              <CloseButton onClick={closeDialog} />
              <h3 className="title-body-bold">
                {t("transactions.retry.steps.title")}
              </h3>
            </div>
            <div className="h-sep mx-[-24px] mt-[20px]" />

            <div className="w-full h-full f-col">
              <DialogStepper>
                <DialogStep
                  stepIndex={RetrySteps.CHECK}
                  currentStepIndex={activeStep}
                  isActive={activeStep === RetrySteps.CHECK}
                >
                  {t("transactions.claim.steps.pre_check.title")}
                </DialogStep>
                <DialogStep
                  stepIndex={RetrySteps.SELECT}
                  currentStepIndex={activeStep}
                  isActive={activeStep === RetrySteps.SELECT}
                >
                  {t("transactions.retry.steps.select.title")}
                </DialogStep>
                <DialogStep
                  stepIndex={RetrySteps.REVIEW}
                  currentStepIndex={activeStep}
                  isActive={activeStep === RetrySteps.REVIEW}
                >
                  {t("common.review")}
                </DialogStep>
                <DialogStep
                  stepIndex={RetrySteps.CONFIRM}
                  currentStepIndex={activeStep}
                  isActive={activeStep === RetrySteps.CONFIRM}
                >
                  {t("common.confirm")}
                </DialogStep>
              </DialogStepper>

              {activeStep === RetrySteps.CHECK ? (
                <ClaimPreCheck
                  tx={bridgeTx}
                  canContinue={canContinue}
                  onCanContinueChange={setCanContinue}
                  hideContinueButton={hideContinueButton}
                  onHideContinueButtonChange={setHideContinueButton}
                  onCloseDialog={closeDialog}
                />
              ) : activeStep === RetrySteps.SELECT ? (
                <RetryOptionStep
                  canContinue={canContinue}
                  onCanContinueChange={setCanContinue}
                />
              ) : activeStep === RetrySteps.REVIEW ? (
                <ReviewStep tx={bridgeTx} />
              ) : activeStep === RetrySteps.CONFIRM ? (
                <ClaimConfirmStep
                  bridgeTx={bridgeTx}
                  // Original `bind:txHash` — the child only READS it, so this is a
                  // read-only prop here. `txHash` starts undefined; ClaimConfirmStep
                  // types it as required, so we forward the local value (cast to
                  // satisfy the prop) and the child guards on truthy `txHash`.
                  txHash={txHash as Hash}
                  onClaim={handleClaimClick}
                  claiming={retrying}
                  canClaim={canContinue}
                  claimingDone={retryDone}
                />
              ) : null}
              <div className="f-col text-left self-end h-full w-full">
                <div className="f-col gap-4 mt-[20px]">
                  <RetryStepNavigation
                    activeStep={activeStep}
                    onActiveStepChange={setActiveStep}
                    canContinue={canContinue}
                    loading={loading}
                    retrying={retrying}
                    onCloseDialog={closeDialog}
                    retryDone={retryDone}
                  />
                </div>
              </div>
            </div>
          </div>
          <button className="overlay-backdrop" data-modal-uuid={dialogId} />
        </dialog>

        <Claim
          ref={claimComponentRef}
          bridgeTx={bridgeTx}
          onError={handleRetryError}
          onClaimingTxSent={handleRetryTxSent}
        />

        <OnAccount change={handleAccountChange} />
      </>
    );
  },
);

export default RetryDialog;
