// packages/taikoon-ui/src/components/core/Toast/Toast.svelte
<script lang="ts" context="module">
  import { toast } from '@zerodevx/svelte-toast';

  import { toastConfig } from '../../../app.config';
  import { uid } from '../../../lib/util/uid';
  import ItemToast from './ItemToast.svelte';
  import type { TypeToast } from './types';

  export type NotificationType = {
    title: string;
    message?: string;
    type?: TypeToast;
    closeManually?: boolean;
  };

  const closeManuallyDefaults: Record<TypeToast, boolean> = {
    // Defaults when no value was provided for closeManually
    success: false,
    error: true,
    warning: false,
    info: false,
    unknown: false,
  };

  function getDefaultCloseBehaviour(type: TypeToast): boolean {
    return closeManuallyDefaults[type];
  }

  export function notify(notificationType: NotificationType) {
    const id = Number(uid());
    const close = () => toast.pop(id);
    const { title, message, type = 'unknown', closeManually = getDefaultCloseBehaviour(type) } = notificationType;

    toast.push({
      id,
      ...(closeManually ? { initial: 0 } : {}),
      component: {
        src: ItemToast,
        props: { type, title, message, close },
      },
    });
  }

  export function successToast(notificationType: NotificationType) {
    notify({
      ...notificationType,
      type: 'success',
    });
  }

  export function errorToast(notificationType: NotificationType) {
    notify({
      ...notificationType,
      type: 'error',
    });
  }

  export function warningToast(notificationType: NotificationType) {
    notify({
      ...notificationType,
      type: 'warning',
    });
  }

  export function infoToast(notificationType: NotificationType) {
    notify({
      ...notificationType,
      type: 'info',
    });
  }

  export function neutralToast(notificationType: NotificationType) {
    notify({
      ...notificationType,
      type: 'unknown',
    });
  }
</script>

<script lang="ts">
  import { SvelteToast } from '@zerodevx/svelte-toast';

  const options: { duration: number } = {
    duration: toastConfig.duration,
  };
</script>

<div class="NotificationToast">
  <SvelteToast {options} />
</div>

<style>
  .NotificationToast {
    --toastContainerRight: auto;
    --toastContainerBottom: auto;
    --toastContainerTop: 77px;
    --toastContainerLeft: calc(50vw - 160px);
    --toastBoxShadow: none;
    --toastWidth: 339px;

    /*
      We need to makes the surroundings disappear in order
      to fully customize the toast with our own component
    */
    --toastBackground: transparent;
    --toastPadding: 0;
    --toastMsgPadding: 0;
    --toastBarWidth: 0;
    --toastBarHeight: 1;
    --toastBtnWidth: 0;
    --toastBtnHeight: 0;
    --toastBtnContent: '';
  }

  /* sm */
  @media (min-width: 640px) {
    .NotificationToast {
      --toastContainerLeft: auto;
      --toastContainerRight: 1rem;
    }
  }

  /* md */
  @media (min-width: 768px) {
    .NotificationToast {
      --toastContainerRight: 2.5rem;
    }
  }
</style>

// packages/bridge-ui-next/src/components/NotificationToast/toast.tsx
"use client";

// Ported from the `context="module"` block of
// src/components/NotificationToast/NotificationToast.svelte.
//
// The original was backed by @zerodevx/svelte-toast and rendered a fully
// custom ItemToast component inside each toast (the chrome of the underlying
// toast lib was stripped via CSS vars so ItemToast controls 100% of the look).
// In the Next app, toasts are hosted by sonner (the <NotificationToast />
// Toaster, mounted in providers.tsx). We reproduce the original behaviour with
// sonner's `toast.custom`, which renders an arbitrary React element as the toast
// body — giving us the exact ItemToast appearance for pixel parity.
//
// Public surface preserved verbatim from the original module script:
//   notify({ title, message?, type?, closeManually? })
//   successToast / errorToast / warningToast / infoToast
//
// `closeManually` (default true for error/warning, false otherwise) kept the
// toast open until dismissed (original passed `initial: 0` to svelte-toast, i.e.
// no auto-dismiss). sonner's `duration: Infinity` reproduces that. `close` maps
// to `toast.dismiss(id)` — the same role as the original `toast.pop(id)`.
//
// NOTE: this file is .tsx because sonner's `toast.custom` requires its render
// callback to return a `React.ReactElement`. Under React 19's types,
// `createElement(...)` yields a `FunctionComponentElement` whose `type` widens
// to a component returning `ReactNode | Promise<ReactNode>`, which is not
// assignable to that `ReactElement`. Emitting JSX produces a plain, correctly
// typed `ReactElement` and avoids a cast.

import { toast } from "sonner";

import { toastConfig } from "@/app.config";

import ItemToast from "./ItemToast";
import type { TypeToast } from "./types";

export type NotificationType = {
  title: string;
  message?: string;
  type?: TypeToast;
  closeManually?: boolean;
};

const duration = toastConfig.duration;

const closeManuallyDefaults: Record<TypeToast, boolean> = {
  // Defaults when no value was provided for closeManually
  success: false,
  error: true,
  warning: true,
  info: false,
  unknown: false,
};

function getDefaultCloseBehaviour(type: TypeToast): boolean {
  return closeManuallyDefaults[type];
}

export function notify(notificationType: NotificationType) {
  const {
    title,
    message,
    type = "unknown",
    closeManually = getDefaultCloseBehaviour(type),
  } = notificationType;

  return toast.custom(
    (id) => (
      <ItemToast
        type={type}
        title={title}
        message={message}
        close={() => toast.dismiss(id)}
      />
    ),
    {
      // closeManually -> no auto-dismiss (original passed `initial: 0`).
      duration: closeManually ? Infinity : duration,
    },
  );
}

export function successToast(notificationType: NotificationType) {
  notify({
    ...notificationType,
    type: "success",
  });
}

export function errorToast(notificationType: NotificationType) {
  notify({
    ...notificationType,
    type: "error",
  });
}

export function warningToast(notificationType: NotificationType) {
  notify({
    ...notificationType,
    type: "warning",
  });
}

export function infoToast(notificationType: NotificationType) {
  notify({
    ...notificationType,
    type: "info",
  });
}
