// packages/bridge-ui-next/src/components/NFTs/NFTList/NFTList.tsx
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { selectedNFTs, selectedToken } from "@/components/Bridge/state";
import { useTranslation } from "@/i18n/useTranslation";
import type { NFT } from "@/libs/token";
import { groupNFTByCollection } from "@/libs/util/groupNFTByCollection";
import { publicEnv } from "@/config/env";

import NFTListItem from "./NFTListItem";

export interface NFTListProps {
  /** Svelte `bind:nfts` (parent passes it; this component never mutates it). */
  nfts: NFT[];
  chainId: number | undefined;
  viewOnly?: boolean;
}

const multiSelectEnabled =
  (publicEnv.NFT_BATCH_TRANSFERS_ENABLED || "false") === "true";

export default function NFTList({
  nfts,
  chainId,
  viewOnly = false,
}: NFTListProps) {
  const { t } = useTranslation();

  const [allChecked, setAllChecked] = useState(false);
  const [checkedAddresses, setCheckedAddresses] = useState<
    Map<string, boolean>
  >(new Map());

  // Latest `nfts` / `chainId` / `checkedAddresses` for the stable callbacks
  // below — keeps callback identity stable (they are passed to every memoized
  // NFTListItem) without changing behavior. Refs are synced in an effect so we
  // never write a ref during render.
  const nftsRef = useRef(nfts);
  const chainIdRef = useRef(chainId);
  const checkedAddressesRef = useRef(checkedAddresses);
  useEffect(() => {
    nftsRef.current = nfts;
    chainIdRef.current = chainId;
    checkedAddressesRef.current = checkedAddresses;
  }, [nfts, chainId, checkedAddresses]);

  const toggleAllAddresses = (nextAllChecked: boolean) => {
    const next = new Map(checkedAddresses);
    nfts.forEach((nft) => {
      if (!chainId) return;

      const address = nft.addresses[chainId];
      if (address) {
        next.set(address, nextAllChecked);
      }
    });
    setCheckedAddresses(next);
  };

  const toggleAddressCheckBox = useCallback((collectionAddress: string) => {
    if (!collectionAddress) return;
    const next = new Map(checkedAddressesRef.current);
    next.set(collectionAddress, !next.get(collectionAddress));
    setCheckedAddresses(next);

    // Mirror the original `checkAllCheckboxes(next)` call inline.
    const currentChainId = chainIdRef.current;
    setAllChecked(
      nftsRef.current.every((nft) => {
        if (!currentChainId) return false;
        const collectionAddress = nft.addresses[currentChainId];
        return Boolean(collectionAddress && next.get(collectionAddress));
      }),
    );
  }, []);

  const selectNFT = useCallback((nft: NFT) => {
    const currentChainId = chainIdRef.current;
    if (!selectedNFTs || !currentChainId || !nft) return;
    const address = nft.addresses[currentChainId];
    const foundNFT = nftsRef.current.find(
      (n) =>
        n.addresses[currentChainId] === address && nft.tokenId === n.tokenId,
    );
    const next = foundNFT ? [foundNFT] : null;
    selectedNFTs.setState(next, true);

    if (next) selectedToken.setState(next[0], true);
  }, []);

  const collections = useMemo(() => groupNFTByCollection(nfts), [nfts]);

  if (nfts.length <= 0) return null;

  return (
    <div className="flex flex-col">
      {multiSelectEnabled && !viewOnly && (
        <div className="form-control">
          <label className="cursor-pointer label">
            <span className="label-text">
              {t("bridge.nft.step.import.select_all")}
            </span>
            <input
              type="checkbox"
              checked={allChecked}
              className="checkbox checkbox-secondary mr-[23px]"
              onChange={(e) => {
                setAllChecked(e.target.checked);
                toggleAllAddresses(e.target.checked);
              }}
            />
          </label>
        </div>
      )}
      {!chainId
        ? "Select a chain"
        : Object.entries(collections).map(([address, nftsGroup]) => (
            <div key={address}>
              {nftsGroup.length > 0 && (
                <>
                  <div className="collection-header">
                    <span className="font-bold text-primary-content">
                      {nftsGroup[0].name}
                    </span>
                    <span className="badge badge-primary badge-outline badge-xs px-[10px] h-[24px] ml-[10px]">
                      <span className="text-xs">{nftsGroup[0].type}</span>
                    </span>
                  </div>
                  <div className="token-ids my-[16px]">
                    {nftsGroup.map((nft) => {
                      const collectionAddress = nft.addresses[chainId];
                      if (collectionAddress === undefined) {
                        return (
                          <div key={`${nft.tokenId}`}>
                            TODO: Address for {nft.name} is undefined
                          </div>
                        );
                      }
                      return (
                        <NFTListItem
                          key={`${nft.tokenId}`}
                          nft={nft}
                          multiSelectEnabled={multiSelectEnabled}
                          checkedAddresses={checkedAddresses}
                          collectionAddress={collectionAddress}
                          toggleAddressCheckBox={toggleAddressCheckBox}
                          selectNFT={selectNFT}
                          viewOnly={viewOnly}
                        />
                      );
                    })}
                  </div>
                  {(Object.keys(collections).length > 1 || nfts.length > 3) && (
                    <div className="h-sep my-[30px]" />
                  )}
                </>
              )}
            </div>
          ))}
    </div>
  );
}

// packages/bridge-ui-v2/src/components/NFTs/NFTList/NFTList.svelte
<script lang="ts">
  import { t } from 'svelte-i18n';

  import { selectedNFTs, selectedToken } from '$components/Bridge/state';
  import { PUBLIC_NFT_BATCH_TRANSFERS_ENABLED } from '$env/static/public';
  import type { NFT } from '$libs/token';
  import { groupNFTByCollection } from '$libs/util/groupNFTByCollection';

  import NftListItem from './NFTListItem.svelte';

  export let nfts: NFT[];
  export let chainId: number | undefined;
  // export let selectedNFT: NFT[] | null = [];
  export let viewOnly = false;

  const multiSelectEnabled = (PUBLIC_NFT_BATCH_TRANSFERS_ENABLED || 'false') === 'true';

  let allChecked = false;
  let checkedAddresses: Map<string, boolean> = new Map();

  const toggleAllAddresses = () => {
    nfts.forEach((nft) => {
      if (!chainId) return;

      const address = nft.addresses[chainId];
      if (address) {
        checkedAddresses.set(address, allChecked);
      }
    });
    checkedAddresses = new Map(checkedAddresses);
  };

  const toggleAddressCheckBox = (collectionAddress: string) => {
    if (!collectionAddress) return;
    checkedAddresses.set(collectionAddress, !checkedAddresses.get(collectionAddress));
    checkedAddresses = new Map(checkedAddresses);
    checkAllCheckboxes();
  };

  const selectNFT = (nft: NFT) => {
    if (!selectedNFTs || !chainId || !nft) return;
    const currentChainId = chainId;
    const address = nft.addresses[currentChainId];
    const foundNFT = nfts.find((n) => n.addresses[currentChainId] === address && nft.tokenId === n.tokenId);
    $selectedNFTs = foundNFT ? [foundNFT] : null;

    if ($selectedNFTs) $selectedToken = $selectedNFTs[0];
  };

  const checkAllCheckboxes = () => {
    allChecked = nfts.every((nft) => {
      if (!chainId) return;
      const collectionAddress = nft.addresses[chainId];
      return collectionAddress && checkedAddresses.get(collectionAddress);
    });
  };

  $: collections = groupNFTByCollection(nfts);
</script>

{#if nfts.length > 0}
  <div class="flex flex-col">
    {#if multiSelectEnabled && !viewOnly}
      <div class="form-control">
        <label class="cursor-pointer label">
          <span class="label-text">{$t('bridge.nft.step.import.select_all')}</span>
          <input
            type="checkbox"
            bind:checked={allChecked}
            class="checkbox checkbox-secondary mr-[23px]"
            on:change={toggleAllAddresses} />
        </label>
      </div>
    {/if}

    {#if !chainId}
      Select a chain
    {:else}
      {#each Object.entries(collections) as [address, nftsGroup] (address)}
        <div>
          {#if nftsGroup.length > 0}
            <div class="collection-header">
              <span class="font-bold text-primary-content">
                {nftsGroup[0].name}
              </span>
              <span class="badge badge-primary badge-outline badge-xs px-[10px] h-[24px] ml-[10px]"
                ><span class="text-xs">{nftsGroup[0].type}</span></span>
            </div>
            <div class="token-ids my-[16px]">
              {#each nftsGroup as nft}
                {@const collectionAddress = nft.addresses[chainId]}
                {#if collectionAddress === undefined}
                  <div>TODO: Address for {nft.name} is undefined</div>
                {:else}
                  <NftListItem
                    {nft}
                    {multiSelectEnabled}
                    {checkedAddresses}
                    {collectionAddress}
                    {toggleAddressCheckBox}
                    {selectNFT}
                    bind:viewOnly />
                {/if}
              {/each}
            </div>
            {#if Object.keys(collections).length > 1 || nfts.length > 3}
              <div class="h-sep my-[30px]" />
            {/if}
          {/if}
        </div>
      {/each}
    {/if}
  </div>
{/if}
