// packages/bridge-ui-v2/src/components/Bridge/NFTBridgeComponents/StepNavigation/StepNavigation.svelte
<script lang="ts">
  import { t } from 'svelte-i18n';

  import { importDone } from '$components/Bridge/state';
  import { BridgeSteps, ImportMethod } from '$components/Bridge/types';
  import { ActionButton } from '$components/Button';

  import { selectedImportMethod } from '../ImportStep/state';
  import StepBack from './StepBack.svelte';

  export let activeStep: BridgeSteps = BridgeSteps.IMPORT;
  export let validatingImport = false;

  let nextStepButtonText: string;

  // const nextStep = () => (activeStep = Math.min(activeStep + 1, BridgeSteps.CONFIRM));

  const getStepText = () => {
    if (activeStep === BridgeSteps.REVIEW) {
      return $t('common.confirm');
    }
    if (activeStep === BridgeSteps.CONFIRM) {
      return $t('common.ok');
    } else {
      return $t('common.continue');
    }
  };

  const handleNextStep = () => {
    if (activeStep === BridgeSteps.IMPORT) {
      activeStep = BridgeSteps.REVIEW;
    } else if (activeStep === BridgeSteps.REVIEW) {
      activeStep = BridgeSteps.CONFIRM;
    } else if (activeStep === BridgeSteps.RECIPIENT) {
      activeStep = BridgeSteps.REVIEW;
    } else if (activeStep === BridgeSteps.CONFIRM) {
      activeStep = BridgeSteps.IMPORT;
    }
  };

  const handlePreviousStep = () => {
    if (activeStep === BridgeSteps.REVIEW) {
      activeStep = BridgeSteps.IMPORT;
    } else if (activeStep === BridgeSteps.CONFIRM) {
      activeStep = BridgeSteps.REVIEW;
    }
  };

  $: showStepNavigation = $selectedImportMethod !== ImportMethod.NONE;

  $: {
    nextStepButtonText = getStepText();
  }
</script>

{#if showStepNavigation}
  <div class="f-col w-full justify-content-center gap-4">
    {#if activeStep === BridgeSteps.IMPORT}
      {#if $selectedImportMethod !== ImportMethod.NONE}
        <ActionButton
          priority="primary"
          disabled={!$importDone}
          loading={validatingImport}
          on:click={() => handleNextStep()}>
          <span class="body-bold">{nextStepButtonText}</span>
        </ActionButton>

        <StepBack on:click={() => ($selectedImportMethod = ImportMethod.NONE)}>{$t('common.back')}</StepBack>
      {/if}
    {/if}
    {#if activeStep === BridgeSteps.REVIEW}
      <ActionButton priority="primary" on:click={() => handleNextStep()}>
        <span class="body-bold">{nextStepButtonText}</span>
      </ActionButton>

      <StepBack on:click={() => handlePreviousStep()}>
        {$t('common.back')}
      </StepBack>
    {/if}

    {#if activeStep === BridgeSteps.RECIPIENT}
      <ActionButton priority="primary" on:click={() => handleNextStep()}>
        <span class="body-bold">{nextStepButtonText}</span>
      </ActionButton>

      <StepBack on:click={() => handlePreviousStep()}>
        {$t('common.back')}
      </StepBack>
    {/if}

    {#if activeStep === BridgeSteps.CONFIRM}
      <!-- <ActionButton priority="primary" disabled={!canProceed} on:click={() => handleNextStep()}>
        <span class="body-bold">{nextStepButtonText}</span>
      </ActionButton> -->

      <StepBack on:click={() => handlePreviousStep()}>
        {$t('common.back')}
      </StepBack>
    {/if}
  </div>
{/if}

// packages/bridge-ui-next/src/components/Bridge/NFTBridgeComponents/StepNavigation/StepNavigation.tsx
"use client";

import {
  calculatingProcessingFee,
  importDone,
  useBridgeState,
} from "@/components/Bridge/state";
import {
  BridgeSteps,
  BridgingStatus,
  ImportMethod,
} from "@/components/Bridge/types";
import { ActionButton } from "@/components/Button";
import { StepBack } from "@/components/Stepper";
import { useTranslation } from "@/i18n/useTranslation";

import {
  selectedImportMethod,
  useSelectedImportMethod,
} from "../ImportStep/state";

export interface StepNavigationProps {
  /** Two-way bound `activeStep` (Svelte `bind:activeStep`). */
  activeStep?: BridgeSteps;
  onActiveStepChange?: (value: BridgeSteps) => void;
  validatingImport?: boolean;
  disabled?: boolean;
  bridgingStatus: BridgingStatus;
}

export default function StepNavigation({
  activeStep = BridgeSteps.IMPORT,
  onActiveStepChange,
  validatingImport = false,
  disabled = false,
  bridgingStatus,
}: StepNavigationProps) {
  const { t } = useTranslation();

  const $selectedImportMethod = useSelectedImportMethod();
  const $importDone = useBridgeState(importDone);
  const $calculatingProcessingFee = useBridgeState(calculatingProcessingFee);

  const getStepText = () => {
    if (activeStep === BridgeSteps.REVIEW) {
      return t("common.confirm");
    }
    if (activeStep === BridgeSteps.CONFIRM) {
      return t("common.ok");
    } else {
      return t("common.continue");
    }
  };

  const handleNextStep = () => {
    if (activeStep === BridgeSteps.IMPORT) {
      onActiveStepChange?.(BridgeSteps.REVIEW);
    } else if (activeStep === BridgeSteps.REVIEW) {
      onActiveStepChange?.(BridgeSteps.CONFIRM);
    } else if (activeStep === BridgeSteps.RECIPIENT) {
      onActiveStepChange?.(BridgeSteps.REVIEW);
    } else if (activeStep === BridgeSteps.CONFIRM) {
      onActiveStepChange?.(BridgeSteps.IMPORT);
    }
  };

  const handlePreviousStep = () => {
    if (activeStep === BridgeSteps.REVIEW) {
      onActiveStepChange?.(BridgeSteps.IMPORT);
    } else if (activeStep === BridgeSteps.CONFIRM) {
      onActiveStepChange?.(BridgeSteps.REVIEW);
    }
  };

  // $: showStepNavigation = $selectedImportMethod !== ImportMethod.NONE;
  const showStepNavigation = $selectedImportMethod !== ImportMethod.NONE;

  // $: { nextStepButtonText = getStepText(); }
  const nextStepButtonText = getStepText();

  // {#if showStepNavigation} ... {/if} — wrapper preserved as a conditional render
  // (rather than an early return) so the inner redundant `!== NONE` re-check, which
  // the source keeps verbatim, isn't narrowed away by control flow analysis.
  if (!showStepNavigation) return null;

  return (
    <div className="f-col w-full justify-content-center gap-4">
      {activeStep === BridgeSteps.IMPORT &&
        (selectedImportMethod.getState() as ImportMethod) !==
          ImportMethod.NONE && (
          <>
            <ActionButton
              priority="primary"
              disabled={!$importDone}
              loading={validatingImport}
              onClick={() => handleNextStep()}
            >
              <span className="body-bold">{nextStepButtonText}</span>
            </ActionButton>

            <StepBack
              onClick={() => selectedImportMethod.setState(ImportMethod.NONE)}
            >
              {t("common.back")}
            </StepBack>
          </>
        )}
      {activeStep === BridgeSteps.REVIEW && (
        <>
          <ActionButton
            priority="primary"
            disabled={$calculatingProcessingFee}
            onClick={() => handleNextStep()}
          >
            <span className="body-bold">{nextStepButtonText}</span>
          </ActionButton>

          <StepBack onClick={() => handlePreviousStep()}>
            {t("common.back")}
          </StepBack>
        </>
      )}

      {activeStep === BridgeSteps.RECIPIENT && (
        <ActionButton priority="primary" onClick={() => handleNextStep()}>
          <span className="body-bold">{nextStepButtonText}</span>
        </ActionButton>
      )}

      {activeStep === BridgeSteps.CONFIRM &&
        (bridgingStatus === BridgingStatus.DONE ? (
          <ActionButton
            disabled={disabled}
            priority="primary"
            onClick={() => handleNextStep()}
          >
            <span className="body-bold">{nextStepButtonText}</span>
          </ActionButton>
        ) : (
          <StepBack onClick={() => handlePreviousStep()}>
            {t("common.back")}
          </StepBack>
        ))}
    </div>
  );
}
