// packages/bridge-ui-next/src/components/Bridge/NFTBridgeComponents/ImportStep/ImportStep.tsx
"use client";

import { useEffect, useRef, useState } from "react";

import {
  destNetwork as destChain,
  importDone,
  selectedNFTs,
  useBridgeState,
} from "@/components/Bridge/state";
import { ImportMethod } from "@/components/Bridge/types";
import { ChainSelector, ChainSelectorType } from "@/components/ChainSelectors";
import { OnAccount } from "@/components/OnAccount";
import { fetchNFTs } from "@/libs/bridge/fetchNFTs";
import type { NFT } from "@/libs/token";
import { account } from "@/stores/account";
import { connectedSourceChain as srcChain } from "@/stores/network";

import ImportActions from "./ImportActions";
import ManualImport from "./ManualImport";
import ScannedImport from "./ScannedImport";
import { selectedImportMethod, useSelectedImportMethod } from "./state";

export interface ImportStepProps {
  /** Two-way bound `validating` (Svelte `bind:validating`). */
  validating?: boolean;
  onValidatingChange?: (value: boolean) => void;
}

export default function ImportStep({
  validating = false,
  onValidatingChange,
}: ImportStepProps) {
  const [foundNFTs, setFoundNFTs] = useState<NFT[]>([]);

  // States
  const [scanning, setScanning] = useState(false);
  const [canProceed, setCanProceed] = useState(false);

  const $selectedImportMethod = useSelectedImportMethod();
  const $destChain = useBridgeState(destChain);

  // foundNFTs is read inside nextPage's pagination check via ScannedImport, but
  // the source scanForNFTs replaces it wholesale; keep a ref for stable reads.
  const foundNFTsRef = useRef<NFT[]>(foundNFTs);
  foundNFTsRef.current = foundNFTs;

  const nextPage = async () => {
    await scanForNFTs(false);
  };

  const scanForNFTs = async (refresh: boolean) => {
    setScanning(true);
    selectedNFTs.setState([]);
    const accountAddress = account.getState()?.address;
    const srcChainId = srcChain.getState()?.id;
    const destChainId = destChain.getState()?.id;
    if (!accountAddress || !srcChainId || !destChainId) return;
    const nftsFromAPIs = await fetchNFTs({
      address: accountAddress,
      chainId: srcChainId,
      refresh,
    });

    setFoundNFTs(nftsFromAPIs.nfts);

    setScanning(false);

    if (nftsFromAPIs.nfts.length > 0) {
      selectedImportMethod.setState(ImportMethod.SCAN);
    }
  };

  const reset = () => {
    setFoundNFTs([]);
    selectedNFTs.setState([]);
    selectedImportMethod.setState(ImportMethod.NONE);
  };

  const onAccountChange = () => {
    reset();
  };

  // $: canImport = ($account?.isConnected && $srcChain?.id && $destChain && !scanning) || false;
  const canImport = Boolean(
    account.getState()?.isConnected &&
      srcChain.getState()?.id &&
      $destChain &&
      !scanning,
  );

  // $: { if (canProceed) { $importDone = true } else { $importDone = false } }
  useEffect(() => {
    importDone.setState(canProceed ? true : false);
  }, [canProceed]);

  // onMount(() => { reset(); });
  useEffect(() => {
    reset();
  }, []);

  return (
    <>
      <div className="f-between-center gap-[16px] mt-[30px]">
        <ChainSelector type={ChainSelectorType.COMBINED} />
      </div>

      <div className="h-sep" />

      {$selectedImportMethod === ImportMethod.MANUAL ? (
        <ManualImport
          validating={validating}
          onValidatingChange={onValidatingChange}
        />
      ) : $selectedImportMethod === ImportMethod.SCAN ? (
        <ScannedImport
          refresh={() => scanForNFTs(true)}
          nextPage={nextPage}
          foundNFTs={foundNFTs}
          onFoundNFTsChange={setFoundNFTs}
          canProceed={canProceed}
          onCanProceedChange={setCanProceed}
        />
      ) : (
        <ImportActions
          scanning={scanning}
          onScanningChange={setScanning}
          canImport={canImport}
          scanForNFTs={() => scanForNFTs(false)}
        />
      )}

      <OnAccount change={onAccountChange} />
    </>
  );
}

// packages/bridge-ui-v2/src/components/Bridge/NFTBridgeSteps/ImportStep/ImportStep.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { t } from 'svelte-i18n';

  import { chainConfig } from '$chainConfig';
  import { Alert } from '$components/Alert';
  import ImportActions from '$components/Bridge/NFTBridgeSteps/ImportStep/ImportActions.svelte';
  import ManualImport from '$components/Bridge/NFTBridgeSteps/ImportStep/ManualImport.svelte';
  import ScannedImport from '$components/Bridge/NFTBridgeSteps/ImportStep/ScannedImport.svelte';
  import { destNetwork as destChain, selectedNFTs } from '$components/Bridge/state';
  import { ImportMethod } from '$components/Bridge/types';
  import CombinedChainSelector from '$components/ChainSelectors/CombinedChainSelector.svelte';
  import { PUBLIC_SLOW_L1_BRIDGING_WARNING } from '$env/static/public';
  import { fetchNFTs } from '$libs/bridge/fetchNFTs';
  import { LayerType } from '$libs/chain';
  import type { NFT } from '$libs/token';
  import { account } from '$stores/account';
  import { network as srcChain } from '$stores/network';

  import { selectedImportMethod } from './state';

  let slowL1Warning = PUBLIC_SLOW_L1_BRIDGING_WARNING || false;

  let foundNFTs: NFT[] = [];

  export let validating = false;

  const scanForNFTs = async () => {
    scanning = true;
    $selectedNFTs = [];
    const accountAddress = $account?.address;
    const srcChainId = $srcChain?.id;
    const destChainId = $destChain?.id;
    if (!accountAddress || !srcChainId || !destChainId) return;
    const nftsFromAPIs = await fetchNFTs(accountAddress, srcChainId);
    foundNFTs = nftsFromAPIs.nfts;

    scanning = false;

    if (foundNFTs.length > 0) {
      $selectedImportMethod = ImportMethod.SCAN;
    }
  };

  const reset = () => {
    foundNFTs = [];
    $selectedNFTs = [];
    $selectedImportMethod = ImportMethod.NONE;
  };

  //  States
  let scanning = false;

  $: canImport = ($account?.isConnected && $srcChain?.id && $destChain && !scanning) || false;

  $: displayL1Warning = slowL1Warning && $destChain?.id && chainConfig[$destChain.id].type === LayerType.L1;

  onMount(() => {
    reset();
  });
</script>

<div class="f-between-center gap-[16px] mt-[30px]">
  <CombinedChainSelector />
</div>

{#if displayL1Warning}
  <Alert type="warning">{$t('bridge.alerts.slow_bridging')}</Alert>
{/if}
<div class="h-sep" />
{#if $selectedImportMethod === ImportMethod.MANUAL}
  <ManualImport bind:validating />
{:else if $selectedImportMethod === ImportMethod.SCAN}
  <ScannedImport {scanForNFTs} bind:foundNFTs />
{:else}
  <ImportActions bind:scanning {canImport} {scanForNFTs} />
{/if}
