// packages/bridge-ui-next/src/components/NFTs/NFTCards/NFTCardGrid.tsx
"use client";

import { useCallback, useEffect, useMemo, useRef } from "react";

import { selectedNFTs, selectedToken } from "@/components/Bridge/state";
import NFTCard from "@/components/NFTs/NFTCards/NFTCard";
import type { NFT } from "@/libs/token";
import { groupNFTByCollection } from "@/libs/util/groupNFTByCollection";
import {
  connectedSourceChain,
  useConnectedSourceChain,
} from "@/stores/network";

export interface NFTCardGridProps {
  /** Svelte `bind:nfts` (the parent passes it; this component never mutates it). */
  nfts?: NFT[];
  viewOnly?: boolean;
}

export default function NFTCardGrid({
  nfts = [],
  viewOnly = false,
}: NFTCardGridProps) {
  const $connectedSourceChain = useConnectedSourceChain();

  // `selectNFT` is passed to every memoized NFTCard, so keep its identity stable.
  // The selected list + chain are read from their vanilla stores at call time;
  // only `nfts` (a prop) is mirrored into a ref (synced in an effect) so the
  // callback can read the latest array without depending on it. Behavior is
  // identical to closing over the values directly — it only runs on card click.
  const nftsRef = useRef(nfts);
  useEffect(() => {
    nftsRef.current = nfts;
  }, [nfts]);

  const selectNFT = useCallback((nft: NFT) => {
    const currentChainId = connectedSourceChain.getState()?.id;

    if (!currentChainId || !nft) return;
    const currentNFTs = nftsRef.current;
    const currentSelected = selectedNFTs.getState();
    const address = nft.addresses[currentChainId];
    const foundNFT = currentNFTs.find(
      (n) =>
        n.addresses[currentChainId] === address && nft.tokenId === n.tokenId,
    );

    if (currentSelected && foundNFT && currentSelected.includes(foundNFT)) {
      // Deselect
      selectedNFTs.setState(
        currentSelected.filter((selected) => selected.tokenId !== nft.tokenId),
        true,
      );
      selectedToken.setState(null, true);
    } else {
      // Select
      const next = foundNFT ? [foundNFT] : null;
      selectedNFTs.setState(next, true);
      if (next) selectedToken.setState(next[0], true);
    }
  }, []);

  const collections = useMemo(() => groupNFTByCollection(nfts), [nfts]);

  return (
    <>
      {Object.entries(collections).map(([address, nftsGroup]) => {
        const chainId = $connectedSourceChain?.id;
        return (
          <div className="" key={address}>
            {nftsGroup.length > 0 && chainId && (
              <>
                <div className="collection-header">
                  <span className="font-bold text-primary-content">
                    {nftsGroup[0].name}
                  </span>
                  <span className="badge badge-primary badge-outline badge-xs px-[10px] h-[24px] ml-[10px]">
                    <span className="text-xs">{nftsGroup[0].type}</span>
                  </span>
                </div>
                <div className="token-ids mt-[16px] grid gap-4 md:grid-cols-3 grid-cols-2">
                  {nftsGroup.map((nft) => (
                    <NFTCard
                      key={`${nft.tokenId}`}
                      nft={nft}
                      selectNFT={selectNFT}
                      viewOnly={viewOnly}
                    />
                  ))}
                </div>
                {(Object.keys(collections).length > 1 || nfts.length > 3) && (
                  <div className="h-sep my-[30px]" />
                )}
              </>
            )}
          </div>
        );
      })}
    </>
  );
}

// packages/bridge-ui/src/components/NFTs/NFTCards/NFTCardGrid.svelte
<script lang="ts">
  import { get } from 'svelte/store';

  import { selectedNFTs, selectedToken } from '$components/Bridge/state';
  import { NFTCard } from '$components/NFTs/NFTCards';
  import type { NFT } from '$libs/token';
  import { groupNFTByCollection } from '$libs/util/groupNFTByCollection';
  import { connectedSourceChain } from '$stores/network';

  export let nfts: NFT[] = [];
  export let viewOnly = false;

  const selectNFT = (nft: NFT) => {
    const currentChainId = get(connectedSourceChain)?.id;

    if (!currentChainId || !nft) return;
    const address = nft.addresses[currentChainId];
    const foundNFT = nfts.find((n) => n.addresses[currentChainId] === address && nft.tokenId === n.tokenId);

    if ($selectedNFTs && foundNFT && $selectedNFTs.includes(foundNFT)) {
      $selectedNFTs = $selectedNFTs.filter((selected) => selected.tokenId !== nft.tokenId); // Deselect
      $selectedToken = null;
    } else {
      $selectedNFTs = foundNFT ? [foundNFT] : null; // Select
      if ($selectedNFTs) $selectedToken = $selectedNFTs[0];
    }
  };

  $: collections = groupNFTByCollection(nfts);
</script>

{#each Object.entries(collections) as [address, nftsGroup] (address)}
  {@const chainId = $connectedSourceChain?.id}
  <div class="">
    {#if nftsGroup.length > 0 && chainId}
      <div class="collection-header">
        <span class="font-bold text-primary-content">
          {nftsGroup[0].name}
        </span>
        <span class="badge badge-primary badge-outline badge-xs px-[10px] h-[24px] ml-[10px]"
          ><span class="text-xs">{nftsGroup[0].type}</span></span>
      </div>
      <div class="token-ids mt-[16px] grid gap-4 md:grid-cols-3 grid-cols-2">
        {#each nftsGroup as nft}
          <NFTCard {nft} {selectNFT} {viewOnly} />
        {/each}
      </div>
      {#if Object.keys(collections).length > 1 || nfts.length > 3}
        <div class="h-sep my-[30px]"></div>
      {/if}
    {/if}
  </div>
{/each}
