// packages/bridge-ui-next/src/components/ConnectButton/ConnectButton.tsx
"use client";

import { useEffect, useState } from "react";

import { ActionButton } from "@/components/Button";
import { Icon } from "@/components/Icon";
import { useResponsive } from "@/hooks/useResponsive";
import { useTranslation } from "@/i18n/useTranslation";
import { getChainImage } from "@/libs/chain";
import { web3modal } from "@/libs/connect";
import { refreshUserBalance, renderEthBalance } from "@/libs/util/balance";
import { shortenAddress } from "@/libs/util/shortenAddress";
import { cn } from "@/lib/utils";
import { useAccount } from "@/stores/account";
import { useEthBalanceStore } from "@/stores/balance";
import { useConnectedSourceChain } from "@/stores/network";

// Svelte: `export let connected = false;` plus implicit `$$props.class`.
export interface ConnectButtonProps {
  connected?: boolean;
  /** Mirrors Svelte's `$$props.class` (applied to the connected-state button). */
  className?: string;
}

export default function ConnectButton({
  connected = false,
  className,
}: ConnectButtonProps) {
  const { t } = useTranslation();

  // Svelte `let web3modalOpen = false`, synced from `web3modal.subscribeState`.
  const [web3modalOpen, setWeb3modalOpen] = useState(false);

  // $: currentChainId = $connectedSourceChain?.id;
  const currentChainId = useConnectedSourceChain((chain) => chain?.id);
  // $: accountAddress = $account?.address || '';
  const accountAddress = useAccount((acc) => acc?.address ?? "");
  // $: balance = $ethBalance || 0n;
  const balance = useEthBalanceStore((b) => b ?? 0n);
  // $: isConnected = connected || $account?.isConnected || false;
  const isAccountConnected = useAccount((acc) => acc?.isConnected ?? false);

  const { isMobile } = useResponsive();

  // $: isConnected = connected || $account?.isConnected || false;
  const isConnected = connected || isAccountConnected || false;
  // $: actuallyConnected = isConnected && accountAddress;
  const actuallyConnected = isConnected && accountAddress;

  function connectWallet() {
    if (web3modalOpen) return;
    web3modal.open();
  }

  // onMount: subscribe to the web3modal state + refresh the eth balance.
  // onDestroy: unsubscribe.
  useEffect(() => {
    const unsubscribe = web3modal.subscribeState((state: { open: boolean }) => {
      setWeb3modalOpen(state.open);
    });
    void refreshUserBalance();
    return () => {
      unsubscribe?.();
    };
  }, []);

  if (actuallyConnected) {
    return (
      <button
        onClick={connectWallet}
        className={cn(
          "rounded-full min-w-[140px] flex items-center justify-center md:pl-[8px] md:pr-[3px] md:max-h-[48px] max-h-[40px] min-h-[40px] wc-parent-glass !border-solid gap-2 font-bold",
          className,
        )}
      >
        <img
          alt="chain icon"
          className="w-[24px] ml-[10px]"
          src={
            (currentChainId && getChainImage(currentChainId)) ||
            "chains/ethereum.svg"
          }
        />
        <span className="flex items-center text-secondary-content justify-self-start gap-4 md:text-normal text-sm">
          {!isMobile && renderEthBalance(balance, 6)}
          <span className="flex items-center justify-center h-[35px] min-w-[133px] text-center text-tertiary-content btn-glass-bg rounded-full px-[10px] py-[4px] bg-tertiary-background">
            {shortenAddress(accountAddress, 4, 6)}
          </span>
        </span>
      </button>
    );
  }

  return (
    <ActionButton
      priority="primary"
      className="!max-w-[215px] !min-h-[32px] !max-h-[48px] !f-items-center !py-0"
      loading={web3modalOpen}
      onClick={connectWallet}
    >
      <div className="flex items-center body-regular space-x-2">
        {web3modalOpen ? (
          <span>{t("wallet.status.connecting")}</span>
        ) : (
          <>
            <Icon
              type="user-circle"
              className="md-show-block"
              fillClass="fill-white"
            />
            <span>{t("wallet.connect")}</span>
          </>
        )}
      </div>
    </ActionButton>
  );
}

// packages/taikoon-ui/src/components/ConnectButton/ConnectButton.svelte
<script lang="ts">
  import { getAccount } from '@wagmi/core';
  import { onDestroy, onMount } from 'svelte';
  import { formatEther } from 'viem';
  import { zeroAddress } from 'viem';

  import { getChainImage } from '$lib/chain';
  import { web3modal } from '$lib/connect';
  import { refreshUserBalance } from '$lib/util/balance';
  import { classNames } from '$lib/util/classNames';
  import { noop } from '$lib/util/noop';
  import { shortenAddress } from '$lib/util/shortenAddress';
  import { getBalance } from '$lib/wagmi';
  import { account } from '$stores/account';
  import { ethBalance } from '$stores/balance';
  import { connectedSourceChain } from '$stores/network';
  import { Button } from '$ui/Button';
  import { config } from '$wagmi-config';

  import type { IAddress } from '../../types';
  export let connected = false;

  let web3modalOpen = false;
  let unsubscribeWeb3Modal = noop;

  function connectWallet() {
    if (web3modalOpen) return;
    web3modal.open();
  }

  function onWeb3Modal(state: { open: boolean }) {
    web3modalOpen = state.open;
  }

  $: currentChainId = $connectedSourceChain?.id;
  $: accountAddress = ($account?.address || zeroAddress) as IAddress;
  $: balance = $ethBalance || 0n;

  onMount(async () => {
    unsubscribeWeb3Modal = web3modal.subscribeState(onWeb3Modal);
    await refreshUserBalance();
  });

  onDestroy(unsubscribeWeb3Modal);

  connectedSourceChain.subscribe(async () => {
    const account = getAccount(config);
    if (!account.address) return;
    balance = await getBalance(account.address);
  });
</script>

{#if connected}
  <button
    on:click={connectWallet}
    class={classNames(
      'border border-divider-border',
      'bg-gradient-to-r from-grey-500-10 to-grey-500-20',
      'rounded-full',
      'flex',
      'items-center',
      'gap-2',
      'font-bold',
    )}>
    <img
      alt="chain icon"
      class="w-[24px] ml-1"
      src={(currentChainId && getChainImage(currentChainId)) || 'chains/ethereum.svg'} />
    <span
      class={classNames(
        'flex items-center',
        'justify-center',
        'text-secondary-content',
        'p-1',
        'gap-2',
        'md:text-normal',
        'text-sm',
      )}
      >{`Ξ ${parseFloat(formatEther(balance)).toFixed(3)}`}
      <span
        class={classNames('flex', 'rounded-full', 'p-2.5', 'bg-neutral-background', 'border border-divider-border')}>
        {#await shortenAddress(accountAddress, 4, 6)}
          ...
        {:then displayAddress}
          {displayAddress}
        {/await}
      </span>
    </span>
  </button>
{:else}
  <Button type="primary" loading={web3modalOpen} iconLeft={'CircleUserRegular'} on:click={connectWallet}>
    {#if web3modalOpen}
      Connecting
    {:else}Connect Wallet
    {/if}
  </Button>
{/if}
