// packages/bridge-ui/src/components/Bridge/SharedBridgeComponents/RecipientStep/DestOwner.svelte
<script lang="ts">
  import { t } from 'svelte-i18n';
  import type { Address } from 'viem';

  import { destNetwork, destOwnerAddress } from '$components/Bridge/state';
  import { ActionButton, CloseButton } from '$components/Button';
  import { Tooltip } from '$components/Tooltip';
  import { isSmartContract } from '$libs/util/isSmartContract';
  import { shortenAddress } from '$libs/util/shortenAddress';
  import { account } from '$stores/account';

  import AddressInput from '../AddressInput/AddressInput.svelte';

  // Public API
  export const clearRecipient = () => {
    if (addressInput) addressInput.clearAddress(); // update UI
    $destOwnerAddress = null; // update state
  };

  export let small = false;
  export let disabled = false;

  let dialogId = `dialog-${crypto.randomUUID()}`;
  let addressInput: AddressInput;

  let modalOpen = false;
  let invalidAddress = false;
  let prevDestOwnerAddress: Maybe<Address> = null;

  let destOwnerIsSmartContract = false;

  function closeModal() {
    modalOpen = false;
  }

  function openModal() {
    modalOpen = true;
    addressInput.focus();
    addEscKeyListener();
  }

  function cancelModal() {
    // Revert change of destOwner address
    $destOwnerAddress = prevDestOwnerAddress;
    removeEscKeyListener();
    closeModal();
  }

  function modalOpenChange(open: boolean) {
    if (open) {
      // Save it in case we want to cancel
      prevDestOwnerAddress = $destOwnerAddress;
    }
  }

  async function onAddressValidation(event: CustomEvent<{ isValidEthereumAddress: boolean; addr: Address }>) {
    const { isValidEthereumAddress, addr } = event.detail;
    if (isValidEthereumAddress) {
      invalidAddress = false;
      if ($destNetwork?.id && (await isSmartContract(addr, $destNetwork.id))) {
        destOwnerIsSmartContract = true;
      } else {
        destOwnerIsSmartContract = false;
        $destOwnerAddress = addr;
      }
    } else {
      invalidAddress = true;
    }
  }

  const resetAddress = () => {
    $destOwnerAddress = $account?.address;
    ethereumAddressBinding = undefined;
    destOwnerIsSmartContract = false;
  };

  let escKeyListener: (event: KeyboardEvent) => void;

  const addEscKeyListener = () => {
    escKeyListener = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        closeModal();
      }
    };
    window.addEventListener('keydown', escKeyListener);
  };

  const removeEscKeyListener = () => {
    window.removeEventListener('keydown', escKeyListener);
  };

  $: modalOpenChange(modalOpen);

  $: ethereumAddressBinding = undefined;

  $: displayedDestOwner = $destOwnerAddress || $account?.address;
</script>

<div class="Recipient f-col">
  {#if small}
    <div class="f-between-center">
      <span class="text-secondary-content">{$t('destOwner.title')}</span>
      {#if displayedDestOwner}
        {shortenAddress(displayedDestOwner, 8, 10)}
        {#if displayedDestOwner !== $account?.address}
          <span class="text-primary-link">| {$t('common.customized')}</span>
        {/if}
      {:else}
        {$t('destOwner.placeholder')}
      {/if}
    </div>
  {:else}
    <div class="f-between-center">
      <div class="flex space-x-2">
        <span class="body-small-bold text-primary-content">{$t('destOwner.title')}</span>
        <Tooltip>
          <h2>{$t('destOwner.tooltip_title')}</h2>
          {$t('destOwner.tooltip')}
        </Tooltip>
      </div>
      {#if !disabled}
        <button class="link" on:click={openModal} on:focus={openModal}>{$t('common.edit')}</button>
      {/if}
    </div>

    <span class="body-small-regular text-secondary-content mt-[4px]">
      {#if displayedDestOwner}
        {shortenAddress(displayedDestOwner, 15, 13)}
        {#if displayedDestOwner !== $account?.address}
          <span class="text-primary-link">| {$t('common.customized')}</span>
        {/if}
      {:else}
        {$t('recipient.placeholder')}
      {/if}
    </span>

    <dialog id={dialogId} class="modal" class:modal-open={modalOpen}>
      <div class="modal-box relative px-6 md:rounded-[20px] bg-neutral-background">
        <CloseButton onClick={cancelModal} />

        <div class="w-full">
          <h3 class="title-body-bold mb-7">{$t('destOwner.title')}</h3>

          <p class="body-regular text-secondary-content mb-3">{$t('destOwner.description')}</p>

          <div class="relative my-[20px]">
            <AddressInput
              bind:this={addressInput}
              bind:ethereumAddress={ethereumAddressBinding}
              on:addressvalidation={onAddressValidation}
              on:clearInput={resetAddress}
              onDialog
              resettable />
          </div>

          {#if destOwnerIsSmartContract}
            <p class="body-regular text-secondary-content mb-3">
              You cannot set a smart contract as destination owner.
            </p>
          {/if}

          <div class="grid grid-cols-2 gap-[20px]">
            <ActionButton on:click={cancelModal} priority="secondary" onPopup>
              <span class="body-bold">{$t('common.cancel')}</span>
            </ActionButton>
            <ActionButton
              priority="primary"
              disabled={invalidAddress || !ethereumAddressBinding || destOwnerIsSmartContract}
              on:click={closeModal}
              onPopup>
              <span class="body-bold">{$t('common.confirm')}</span>
            </ActionButton>
          </div>
        </div>
      </div>
    </dialog>
  {/if}
</div>

// packages/bridge-ui-next/src/components/Bridge/SharedBridgeComponents/RecipientStep/DestOwner.tsx
"use client";

import {
  forwardRef,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import type { Address } from "viem";

import {
  destNetwork,
  destOwnerAddress,
  useBridgeState,
} from "@/components/Bridge/state";
import { ActionButton, CloseButton } from "@/components/Button";
import { Tooltip } from "@/components/Tooltip";
import { isSmartContract } from "@/libs/util/isSmartContract";
import { shortenAddress } from "@/libs/util/shortenAddress";
import { account, useAccount } from "@/stores/account";
import { cn } from "@/lib/utils";
import { useTranslation } from "@/i18n/useTranslation";

import AddressInput, {
  type AddressInputHandle,
} from "../AddressInput/AddressInput";

/** Public API (Svelte `export const clearRecipient`). */
export interface DestOwnerHandle {
  clearRecipient: () => void;
}

export interface DestOwnerProps {
  small?: boolean;
  disabled?: boolean;
}

const DestOwner = forwardRef<DestOwnerHandle, DestOwnerProps>(
  function DestOwner({ small = false, disabled = false }, ref) {
    const { t } = useTranslation();

    const dialogId = `dialog-${useId()}`;
    const addressInputRef = useRef<AddressInputHandle>(null);

    const [modalOpen, setModalOpen] = useState(false);
    const [invalidAddress, setInvalidAddress] = useState(false);
    const prevDestOwnerAddressRef = useRef<Maybe<Address>>(null);

    const [destOwnerIsSmartContract, setDestOwnerIsSmartContract] =
      useState(false);

    // `ethereumAddressBinding` is a constant `undefined` in the source (`$: ethereumAddressBinding = undefined`).
    const [ethereumAddressBinding, setEthereumAddressBinding] = useState<
      Address | string | undefined
    >(undefined);

    const $destOwnerAddress = useBridgeState(destOwnerAddress);
    const $account = useAccount((s) => s);

    const escKeyListenerRef = useRef<((event: KeyboardEvent) => void) | null>(
      null,
    );

    // Public API.
    useImperativeHandle(
      ref,
      () => ({
        clearRecipient: () => {
          if (addressInputRef.current) addressInputRef.current.clearAddress(); // update UI
          destOwnerAddress.setState(() => null, true); // update state
        },
      }),
      [],
    );

    function closeModal() {
      setModalOpen(false);
    }

    function openModal() {
      setModalOpen(true);
      addressInputRef.current?.focus();
      addEscKeyListener();
    }

    function cancelModal() {
      // Revert change of destOwner address
      destOwnerAddress.setState(
        () => prevDestOwnerAddressRef.current ?? null,
        true,
      );
      removeEscKeyListener();
      closeModal();
    }

    // $: modalOpenChange(modalOpen)
    useEffect(() => {
      if (modalOpen) {
        // Save it in case we want to cancel
        prevDestOwnerAddressRef.current = destOwnerAddress.getState();
      }
    }, [modalOpen]);

    async function onAddressValidation(detail: {
      isValidEthereumAddress: boolean;
      addr: Address | string;
    }) {
      const { isValidEthereumAddress, addr } = detail;
      if (isValidEthereumAddress) {
        setInvalidAddress(false);
        const dest = destNetwork.getState();
        if (dest?.id && (await isSmartContract(addr as Address, dest.id))) {
          setDestOwnerIsSmartContract(true);
        } else {
          setDestOwnerIsSmartContract(false);
          destOwnerAddress.setState(() => addr as Address, true);
        }
      } else {
        setInvalidAddress(true);
      }
    }

    // on:clearInput={resetAddress}
    const resetAddress = () => {
      destOwnerAddress.setState(
        () => account.getState()?.address ?? null,
        true,
      );
      setEthereumAddressBinding(undefined);
      setDestOwnerIsSmartContract(false);
    };

    const addEscKeyListener = () => {
      const listener = (event: KeyboardEvent) => {
        if (event.key === "Escape") {
          closeModal();
        }
      };
      escKeyListenerRef.current = listener;
      window.addEventListener("keydown", listener);
    };

    const removeEscKeyListener = () => {
      if (escKeyListenerRef.current) {
        window.removeEventListener("keydown", escKeyListenerRef.current);
      }
    };

    useEffect(() => {
      return () => removeEscKeyListener();
    }, []);

    // $: displayedDestOwner = $destOwnerAddress || $account?.address;
    const displayedDestOwner = $destOwnerAddress || $account?.address;

    return (
      <div className="Recipient f-col">
        {small ? (
          <div className="f-between-center">
            <span className="text-secondary-content">
              {t("destOwner.title")}
            </span>
            {displayedDestOwner ? (
              <>
                {shortenAddress(displayedDestOwner, 8, 10)}
                {displayedDestOwner !== $account?.address && (
                  <span className="text-primary-link">
                    | {t("common.customized")}
                  </span>
                )}
              </>
            ) : (
              t("destOwner.placeholder")
            )}
          </div>
        ) : (
          <>
            <div className="f-between-center">
              <div className="flex space-x-2">
                <span className="body-small-bold text-primary-content">
                  {t("destOwner.title")}
                </span>
                <Tooltip>
                  <h2>{t("destOwner.tooltip_title")}</h2>
                  {t("destOwner.tooltip")}
                </Tooltip>
              </div>
              {!disabled && (
                <button
                  className="link"
                  onClick={openModal}
                  onFocus={openModal}
                >
                  {t("common.edit")}
                </button>
              )}
            </div>

            <span className="body-small-regular text-secondary-content mt-[4px]">
              {displayedDestOwner ? (
                <>
                  {shortenAddress(displayedDestOwner, 15, 13)}
                  {displayedDestOwner !== $account?.address && (
                    <span className="text-primary-link">
                      | {t("common.customized")}
                    </span>
                  )}
                </>
              ) : (
                t("recipient.placeholder")
              )}
            </span>

            <dialog
              id={dialogId}
              className={cn("modal", modalOpen && "modal-open")}
            >
              <div className="modal-box relative px-6 md:rounded-[20px] bg-neutral-background">
                <CloseButton onClick={cancelModal} />

                <div className="w-full">
                  <h3 className="title-body-bold mb-7">
                    {t("destOwner.title")}
                  </h3>

                  <p className="body-regular text-secondary-content mb-3">
                    {t("destOwner.description")}
                  </p>

                  <div className="relative my-[20px]">
                    <AddressInput
                      ref={addressInputRef}
                      ethereumAddress={ethereumAddressBinding}
                      onEthereumAddressChange={setEthereumAddressBinding}
                      onAddressValidation={onAddressValidation}
                      onClearInput={resetAddress}
                      onDialog
                      resettable
                    />
                  </div>

                  {destOwnerIsSmartContract && (
                    <p className="body-regular text-secondary-content mb-3">
                      You cannot set a smart contract as destination owner.
                    </p>
                  )}

                  <div className="grid grid-cols-2 gap-[20px]">
                    <ActionButton
                      onClick={cancelModal}
                      priority="secondary"
                      onPopup
                    >
                      <span className="body-bold">{t("common.cancel")}</span>
                    </ActionButton>
                    <ActionButton
                      priority="primary"
                      disabled={
                        invalidAddress ||
                        !ethereumAddressBinding ||
                        destOwnerIsSmartContract
                      }
                      onClick={closeModal}
                      onPopup
                    >
                      <span className="body-bold">{t("common.confirm")}</span>
                    </ActionButton>
                  </div>
                </div>
              </div>
            </dialog>
          </>
        )}
      </div>
    );
  },
);

export default DestOwner;
