// packages/bridge-ui-v2/src/components/SideNavigation/SideNavigation.svelte
<script lang="ts" context="module">
  export const drawerToggleId = 'side-drawer-toggle';
</script>

<script lang="ts">
  import { t } from 'svelte-i18n';

  import { page } from '$app/stores';
  import { Icon } from '$components/Icon';
  import { LinkButton } from '$components/LinkButton';
  import { LogoWithText } from '$components/Logo';
  import { PUBLIC_GUIDE_URL, PUBLIC_L2_EXPLORER_URL } from '$env/static/public';

  let drawerToggleElem: HTMLInputElement;

  $: isBridgePage = $page.route.id === '/' || $page.route.id === '/nft';
  $: isFaucetPage = $page.route.id === '/faucet';
  $: isActivitiesPage = $page.route.id === '/activities';

  function closeDrawer() {
    drawerToggleElem.checked = false;
  }

  function onMenuKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape' || event.key === 'Enter') {
      closeDrawer();
    }
  }

  function getIconFillClass(active: boolean) {
    return active ? 'fill-white' : 'fill-primary-icon';
  }
</script>

<div class="drawer md:drawer-open">
  <input id={drawerToggleId} type="checkbox" class="drawer-toggle" bind:this={drawerToggleElem} />

  <div class="drawer-content relative">
    <slot />
  </div>

  <!-- Side drawer's z-index (20) must be greater than content's header (10)-->
  <div class="drawer-side z-20">
    <label for={drawerToggleId} class="drawer-overlay" />

    <!--
      Slow transitions can be pretty annoying after a while.
      Let's reduce it to 100ms for a better experience.
    -->
    <div class="w-h-full !duration-100">
      <header class="flex justify-end py-[20px] px-4 md:hidden">
        <button on:click={closeDrawer} class="h-9">
          <Icon type="x-close" fillClass="fill-primary-icon" size={24} />
        </button>
      </header>

      <aside
        class="
        h-full
        px-[20px]
        md:mt-0
        md:px-4
        md:py-8
        md:w-[226px]
        md:border-r
        md:border-r-divider-border">
        <a href="/" class="hidden md:inline-block">
          <LogoWithText />
        </a>
        <div role="button" tabindex="0" on:click={closeDrawer} on:keydown={onMenuKeydown}>
          <ul class="menu p-0 md:pt-10 space-y-2">
            <li>
              <LinkButton active={isBridgePage}>
                <Icon type="bridge" fillClass={getIconFillClass(isBridgePage)} />
                <span>{$t('nav.bridge')}</span>
              </LinkButton>
            </li>
            <li>
              <LinkButton href="/faucet" active={isFaucetPage}>
                <Icon type="faucet" fillClass={getIconFillClass(isFaucetPage)} />
                <span>{$t('nav.faucet')}</span>
              </LinkButton>
            </li>
            <li>
              <LinkButton href="/activities" active={isActivitiesPage}>
                <Icon type="activities" fillClass={getIconFillClass(isActivitiesPage)} />
                <span>{$t('nav.activities')}</span>
              </LinkButton>
            </li>
            <li>
              <LinkButton href={PUBLIC_L2_EXPLORER_URL} external>
                <Icon type="explorer" />
                <span>{$t('nav.explorer')}</span>
              </LinkButton>
            </li>
            <li>
              <LinkButton href={PUBLIC_GUIDE_URL} external>
                <Icon type="guide" />
                <span>{$t('nav.guide')}</span>
              </LinkButton>
            </li>
          </ul>
        </div>
      </aside>
    </div>
  </div>
</div>

// packages/bridge-ui-next/src/components/SideNavigation/SideNavigation.tsx
"use client";

import { usePathname } from "next/navigation";
import {
  useCallback,
  useMemo,
  useRef,
  type KeyboardEvent,
  type ReactNode,
} from "react";

import BridgeTabs from "@/components/Bridge/BridgeTabs";
import { Icon } from "@/components/Icon";
import { LinkButton } from "@/components/LinkButton";
import { ThemeButton } from "@/components/ThemeButton";
import { chainConfig } from "@/config/generated/chainConfig";
import { publicEnv } from "@/config/env";
import { useTranslation } from "@/i18n/useTranslation";
import { useConnectedSourceChain } from "@/stores/network";

import { sideNavigationTabs } from "./navigationItems";

export const drawerToggleId = "side-drawer-toggle";

export interface SideNavigationProps {
  /** Controlled drawer-open flag (mirrors svelte's two-way bound `sideBarOpen`). */
  sideBarOpen: boolean;
  /** Emitted when the component closes the drawer (mirrors `sideBarOpen = false`). */
  onSideBarOpenChange?: (open: boolean) => void;
  /** Default slot content rendered inside `.drawer-content`. */
  children?: ReactNode;
}

/** Narrow accessor for the (placeholder-typed) generated chainConfig block explorer url. */
function getExplorerUrl(chainId: number | undefined): string | undefined {
  if (chainId === undefined) return undefined;
  const entry = (chainConfig as Record<string, unknown>)[String(chainId)] as
    | { blockExplorers?: { default?: { url?: string } } }
    | undefined;
  return entry?.blockExplorers?.default?.url;
}

export default function SideNavigation({
  onSideBarOpenChange,
  children,
}: SideNavigationProps) {
  const { t } = useTranslation();
  const pathname = usePathname();
  const connectedSourceChain = useConnectedSourceChain();

  const drawerToggleElem = useRef<HTMLInputElement>(null);

  const testnetName = publicEnv.TESTNET_NAME || "";

  const closeDrawer = useCallback(() => {
    if (!drawerToggleElem.current) return;
    drawerToggleElem.current.checked = false;
    onSideBarOpenChange?.(false);
  }, [onSideBarOpenChange]);

  const onMenuKeydown = useCallback(
    (event: KeyboardEvent) => {
      if (event.key === "Escape" || event.key === "Enter") {
        closeDrawer();
      }
    },
    [closeDrawer],
  );

  function getIconFillClass(active: boolean) {
    return active ? "fill-white" : "fill-primary-icon";
  }

  const isFaucetPage = useMemo(() => pathname === "/faucet", [pathname]);

  return (
    <div className=" drawer lg:drawer-open">
      <input
        id={drawerToggleId}
        type="checkbox"
        className="drawer-toggle"
        ref={drawerToggleElem}
      />
      <div className="drawer-content relative f-col w-full">{children}</div>

      <div className="drawer-side z-20 pt-[81px] lg:pt-[20px] h-full">
        <label htmlFor={drawerToggleId} className="drawer-overlay" />

        {/*
          Slow transitions can be pretty annoying after a while.
          Let's reduce it to 100ms for a better experience.
        */}
        <div className="w-full !duration-100">
          <aside
            className="
        h-full
        px-[20px]
        lg:mt-0
        lg:px-4
        lg:w-[226px]
      "
          >
            <div className="hidden lg:inline-block"></div>
            <div
              role="button"
              tabIndex={0}
              onClick={closeDrawer}
              onKeyPress={closeDrawer}
            >
              <BridgeTabs
                className="lg:hidden flex flex-1 mb-[40px] mt-[20px]"
                onClick={closeDrawer}
              />
            </div>
            <div
              role="button"
              tabIndex={0}
              onClick={closeDrawer}
              onKeyDown={onMenuKeydown}
            >
              <ul className="menu p-0 space-y-2">
                {sideNavigationTabs.map((tab) => (
                  <li key={tab.routeId}>
                    <LinkButton
                      href={tab.href}
                      active={pathname === tab.routeId}
                      onClick={closeDrawer}
                    >
                      <Icon
                        type={tab.icon}
                        fillClass={getIconFillClass(pathname === tab.routeId)}
                      />
                      <span>{t(tab.label)}</span>
                    </LinkButton>
                  </li>
                ))}
                {testnetName !== "" && (
                  <li>
                    <LinkButton href="/faucet" active={isFaucetPage}>
                      <Icon
                        type="faucet"
                        fillClass={getIconFillClass(isFaucetPage)}
                      />
                      <span>{t("nav.faucet")}</span>
                    </LinkButton>
                  </li>
                )}
                {publicEnv.DEFAULT_SWAP_URL &&
                  publicEnv.DEFAULT_SWAP_URL !== "" && (
                    <li className="border-t border-t-divider-border pt-2">
                      <LinkButton href={publicEnv.DEFAULT_SWAP_URL} external>
                        <Icon type="swap" />
                        <span>{t("nav.swap")}</span>
                      </LinkButton>
                    </li>
                  )}
                <li>
                  <LinkButton
                    href={
                      connectedSourceChain
                        ? getExplorerUrl(connectedSourceChain.id)
                        : publicEnv.DEFAULT_EXPLORER
                    }
                    external
                  >
                    <Icon type="explorer" />
                    <span>{t("nav.explorer")}</span>
                  </LinkButton>
                </li>
                <li>
                  <LinkButton href={publicEnv.GUIDE_URL} external>
                    <Icon type="guide" />
                    <span>{t("nav.guide")}</span>
                  </LinkButton>
                </li>
              </ul>
            </div>
            <ul className="">
              <li>
                <div className="p-3 rounded-full flex lg:hidden justify-start content-center">
                  <Icon type="settings" />
                  <div className="flex justify-between w-full pl-[6px]">
                    <span className="text-base">{t("nav.theme")}</span>
                    <ThemeButton mobile />
                  </div>
                </div>
              </li>
            </ul>
          </aside>
        </div>
      </div>
    </div>
  );
}
