// packages/bridge-ui-next/src/components/Transactions/Status/Status.tsx
"use client";

// React port of
// components/Transactions/Status/Status.svelte.
//
// COMPONENT CONVENTION mapping:
//   - `export let bridgeTx / bridgeTxStatus / textOnly` -> typed props.
//   - `bind:bridgeTxStatus` (two-way) -> controlled `bridgeTxStatus` prop +
//     `onBridgeTxStatusChange`. The original mutates `bridgeTxStatus` inside
//     `onStatusChange` and `onMount`; both are mirrored into local state seeded
//     from the prop and reported up.
//   - `dispatch('statusChange', status)`     -> `onStatusChange(status)`.
//   - `dispatch('openModal', detail)`        -> `onOpenModal(detail)`.
//   - `dispatch('transactionRemoved', tx)`   -> `onTransactionRemoved(tx)`.
//   - `onInsufficientFunds` is accepted (callers pass it) but, like the original
//     Svelte component, is never invoked here — kept optional for API parity.
//   - Reactive `$: showManualClaimEntry = ...`            -> useMemo.
//   - Reactive `$: if (hasError && $account.address) {...}` -> useEffect.
//   - `onMount`/`onDestroy` (start/stop polling)          -> useEffect + cleanup.
//   - Store `$account`               -> `useAccount` hook over the vanilla account store.
//   - Store `$connectedSourceChain`  -> `useConnectedSourceChain` hook.
//   - svelte-i18n `$t(key)`          -> react-i18next `t(key)`.
//   - `on:click`                     -> `onClick`.
//
// DOM / Tailwind class strings preserved verbatim for pixel parity.

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { Spinner } from "@/components/Spinner";
import { StatusDot } from "@/components/StatusDot";
import { type BridgeTransaction, MessageStatus } from "@/libs/bridge";
import { isTransactionProcessable } from "@/libs/bridge/isTransactionProcessable";
import { PollingEvent, startPolling } from "@/libs/polling/messageStatusPoller";
import { bridgeTxService } from "@/libs/storage";
import { isBridgePaused } from "@/libs/util/checkForPausedContracts";
import { useTranslation } from "@/i18n/useTranslation";
import { useAccount } from "@/stores/account";
import { useConnectedSourceChain } from "@/stores/network";

import {
  assertBridgeNotPaused,
  shouldShowManualClaimEntry,
} from "./statusHelpers";

export interface StatusProps {
  bridgeTx: BridgeTransaction;
  /** Two-way `bind:bridgeTxStatus`. */
  bridgeTxStatus: Maybe<MessageStatus>;
  onBridgeTxStatusChange?: (status: Maybe<MessageStatus>) => void;
  textOnly?: boolean;
  /** Svelte `dispatch('statusChange', status)`. */
  onStatusChange?: (status: MessageStatus) => void;
  /** Svelte `dispatch('openModal', detail)`. */
  onOpenModal?: (detail: string) => void;
  /** Svelte `dispatch('transactionRemoved', bridgeTx)`. */
  onTransactionRemoved?: (bridgeTx: BridgeTransaction) => void;
  /** Accepted for caller API parity; unused (matches original Svelte). */
  onInsufficientFunds?: () => void;
}

export default function Status({
  bridgeTx,
  bridgeTxStatus: bridgeTxStatusProp,
  onBridgeTxStatusChange,
  textOnly = false,
  onStatusChange,
  onOpenModal,
  onTransactionRemoved,
}: StatusProps) {
  const { t } = useTranslation();

  const $account = useAccount((a) => a);
  const $connectedSourceChain = useConnectedSourceChain();

  // Two-way `bind:bridgeTxStatus`.
  const [bridgeTxStatus, setBridgeTxStatusState] =
    useState<Maybe<MessageStatus>>(bridgeTxStatusProp);
  const setBridgeTxStatus = useCallback(
    (status: Maybe<MessageStatus>) => {
      setBridgeTxStatusState(status);
      onBridgeTxStatusChange?.(status);
    },
    [onBridgeTxStatusChange],
  );
  useEffect(() => {
    setBridgeTxStatusState(bridgeTxStatusProp);
  }, [bridgeTxStatusProp]);

  // UI state
  const [isProcessable, setIsProcessable] = useState(false); // bridge tx state to be processed: claimed/retried/released
  const pollingRef = useRef<ReturnType<typeof startPolling> | null>(null);
  const [loading] = useState<false | string>(false);
  const [hasError, setHasError] = useState(false);

  // $: showManualClaimEntry = shouldShowManualClaimEntry({...})
  const showManualClaimEntry = useMemo(
    () =>
      shouldShowManualClaimEntry({
        bridgeTxStatus,
        isProcessable,
        processingFee: bridgeTx.processingFee,
      }),
    [bridgeTxStatus, isProcessable, bridgeTx.processingFee],
  );

  const onProcessable = useCallback((isTxProcessable: boolean) => {
    setIsProcessable(isTxProcessable);
  }, []);

  const onStatusChangeHandler = useCallback(
    (status: MessageStatus) => {
      // Keeping model and UI in sync
      bridgeTx.msgStatus = status;
      setBridgeTxStatus(status);
      onStatusChange?.(status);
    },
    [bridgeTx, setBridgeTxStatus, onStatusChange],
  );

  async function handleRetryClick() {
    assertBridgeNotPaused(await isBridgePaused());
    if (!$connectedSourceChain || !$account?.address) return;
    // retryModalOpen = true;
    onOpenModal?.("retry");
  }

  async function handleReleaseClick() {
    assertBridgeNotPaused(await isBridgePaused());
    if (!$connectedSourceChain || !$account?.address) return;
    // releaseModalOpen = true;
    onOpenModal?.("release");
  }

  async function handleClaimClick() {
    assertBridgeNotPaused(await isBridgePaused());
    if (!$connectedSourceChain || !$account?.address) return;

    // claimModalOpen = true;
    onOpenModal?.("claim");
  }

  async function handleTryClaimClick() {
    assertBridgeNotPaused(await isBridgePaused());
    if (!$connectedSourceChain || !$account?.address) return;

    onOpenModal?.("try_claim");
  }

  // $: if (hasError && $account.address) { ... }
  useEffect(() => {
    if (hasError && $account?.address) {
      if (
        bridgeTxService.transactionIsStoredLocally($account.address, bridgeTx)
      ) {
        // If we can't start polling, it maybe an old/outdated transaction in the local storage, so we remove it
        bridgeTxService.removeTransactions($account.address, [bridgeTx]);
        if (
          !bridgeTxService.transactionIsStoredLocally(
            $account.address,
            bridgeTx,
          )
        ) {
          onTransactionRemoved?.(bridgeTx);
        }
      }
    }
  }, [hasError, $account?.address, bridgeTx, onTransactionRemoved]);

  // onMount: seed status, resolve processability, start polling.
  // onDestroy: stop polling.
  useEffect(() => {
    let cancelled = false;

    (async () => {
      if (bridgeTx && $account?.address) {
        setBridgeTxStatus(bridgeTx.msgStatus);

        // Can we start claiming/retrying/releasing?
        const processable = await isTransactionProcessable(bridgeTx);
        if (cancelled) return;
        setIsProcessable(processable);

        try {
          const polling = startPolling(bridgeTx);
          pollingRef.current = polling;

          // If there is no emitter, means the bridgeTx is already DONE
          // so we do nothing here
          if (polling?.emitter) {
            // The following listeners will trigger change in the UI
            polling.emitter.on(PollingEvent.PROCESSABLE, onProcessable);
            polling.emitter.on(PollingEvent.STATUS, onStatusChangeHandler);
          }
        } catch (err) {
          console.warn("Cannot start polling", err);
          setHasError(true);
        }
      }
    })();

    return () => {
      cancelled = true;
      if (pollingRef.current) {
        pollingRef.current.destroy();
        pollingRef.current = null;
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className="Status f-items-center space-x-1">
      {showManualClaimEntry ? (
        textOnly ? (
          <>
            <StatusDot type="pending" />
            <span>{t("transactions.status.processing.name")}</span>
          </>
        ) : (
          <button className="status-btn" onClick={handleTryClaimClick}>
            {t("transactions.button.try_claim")}
          </button>
        )
      ) : !isProcessable ? (
        <>
          <StatusDot type="pending" />
          <span>{t("transactions.status.processing.name")}</span>
        </>
      ) : loading ? (
        <div className="f-items-center space-x-2">
          <Spinner />
          <span>{t(`transactions.status.${loading}`)}</span>
        </div>
      ) : bridgeTxStatus === MessageStatus.NEW ? (
        textOnly ? (
          <>
            <StatusDot type="pending" />
            <span>{t("transactions.status.claimable")}</span>
          </>
        ) : (
          <button className="status-btn" onClick={handleClaimClick}>
            {t("transactions.button.claim")}
          </button>
        )
      ) : bridgeTxStatus === MessageStatus.RETRIABLE ? (
        textOnly ? (
          <>
            <StatusDot type="pending" />
            <span>{t("transactions.status.retriable")}</span>
          </>
        ) : (
          <button className="status-btn" onClick={handleRetryClick}>
            {t("transactions.button.retry")}
          </button>
        )
      ) : bridgeTxStatus === MessageStatus.DONE ? (
        <>
          <StatusDot type="success" />
          <span>{t("transactions.status.claimed.name")}</span>
        </>
      ) : bridgeTxStatus === MessageStatus.FAILED ? (
        textOnly ? (
          <>
            <StatusDot type="pending" />
            <span>{t("transactions.status.releasable")}</span>
          </>
        ) : (
          <button className="status-btn" onClick={handleReleaseClick}>
            {t("transactions.button.release")}
          </button>
        )
      ) : bridgeTxStatus === MessageStatus.RECALLED ? (
        <>
          <StatusDot type="error" />
          <span>{t("transactions.status.released.name")}</span>
        </>
      ) : (
        <>
          {/* TODO: look into this possible state */}
          <StatusDot type="error" />
          <span>{t("transactions.status.error.name")}</span>
        </>
      )}
    </div>
  );
}

// packages/bridge-ui-v2/src/components/Activities/Status.svelte
<script lang="ts">
  import { error } from '@sveltejs/kit';
  import { type Address, fetchBalance, switchNetwork } from '@wagmi/core';
  import { onDestroy, onMount } from 'svelte';
  import { t } from 'svelte-i18n';
  import { parseEther, UserRejectedRequestError } from 'viem';

  import {
    errorToast,
    infoToast,
    successToast,
    warningToast,
  } from '$components/NotificationToast/NotificationToast.svelte';
  import { StatusDot } from '$components/StatusDot';
  import { statusComponent } from '$config';
  import { bridges, type BridgeTransaction, MessageStatus } from '$libs/bridge';
  import { PollingEvent, startPolling } from '$libs/bridge/bridgeTxMessageStatusPoller';
  import { isBridgeTxProcessable } from '$libs/bridge/isBridgeTxProcessable';
  import { chains, chainUrlMap } from '$libs/chain';
  import {
    InsufficientBalanceError,
    InvalidProofError,
    NotConnectedError,
    ProcessMessageError,
    ReleaseError,
    RetryError,
  } from '$libs/error';
  import { getConnectedWallet } from '$libs/util/getConnectedWallet';
  import { getLogger } from '$libs/util/logger';
  import { account } from '$stores/account';
  import { network } from '$stores/network';
  import { pendingTransactions } from '$stores/pendingTransactions';

  const log = getLogger('components:Status');

  export let bridgeTx: BridgeTransaction;

  let polling: ReturnType<typeof startPolling>;

  // UI state
  let processable = false; // bridge tx state to be processed: claimed/retried/released
  let bridgeTxStatus: Maybe<MessageStatus>;

  // TODO: enum?
  let loading: 'claiming' | 'releasing' | false = false;

  function onProcessable(isTxProcessable: boolean) {
    processable = isTxProcessable;
  }

  function onStatusChange(status: MessageStatus) {
    // Keeping model and UI in sync
    bridgeTxStatus = bridgeTx.status = status;
  }

  async function ensureCorrectChain(currentChainId: number, wannaBeChainId: number) {
    const isCorrectChain = currentChainId === wannaBeChainId;
    log(`Are we on the correct chain? ${isCorrectChain}`);

    if (!isCorrectChain) {
      // TODO: shouldn't we inform the user about this change? wallet will popup,
      //       but it's not clear why
      await switchNetwork({ chainId: wannaBeChainId });
    }
  }

  async function checkEnoughBalance(address: Address) {
    const balance = await fetchBalance({ address });
    if (balance.value < parseEther(String(statusComponent.minimumEthToClaim))) {
      throw new InsufficientBalanceError('user has insufficient balance');
    }
  }

  async function claim() {
    if (!$network || !$account?.address) return;

    loading = 'claiming';

    try {
      const { msgHash, message } = bridgeTx;

      if (!msgHash || !message) {
        throw new Error('Missing msgHash or message');
      }

      // Step 1: make sure the user is on the correct chain
      await ensureCorrectChain(Number($network.id), Number(bridgeTx.destChainId));

      // Step 2: make sure the user has enough balance on the destination chain
      await checkEnoughBalance($account.address);

      // Step 3: Find out the type of bridge: ETHBridge, ERC20Bridge, etc
      const bridge = bridges[bridgeTx.tokenType];

      // Step 4: get the user's wallet
      // TODO: do we really need to pass the chainId here? we are already on the dest chain
      const wallet = await getConnectedWallet(Number(bridgeTx.destChainId));

      log(`Claiming ${bridgeTx.tokenType} for transaction`, bridgeTx);

      // Step 5: Call claim() method on the bridge
      const txHash = await bridge.claim({ msgHash, message, wallet });

      const { explorerUrl } = chainUrlMap[Number(bridgeTx.destChainId)];

      infoToast(
        $t('activities.actions.claim.tx', {
          values: {
            token: bridgeTx.symbol,
            url: `${explorerUrl}/tx/${txHash}`,
          },
        }),
      );

      await pendingTransactions.add(txHash, $network.id);

      successToast(
        $t('activities.actions.claim.success', {
          values: {
            network: $network.name,
          },
        }),
      );
    } catch (err) {
      console.error(err);

      switch (true) {
        case err instanceof NotConnectedError:
          warningToast($t('messages.account.required'));
          break;
        case err instanceof UserRejectedRequestError:
          warningToast($t('activities.actions.claim_rejected'));
          break;
        case err instanceof InsufficientBalanceError:
          errorToast($t('activities.errors.insufficient_balance'));
          break;
        case err instanceof InvalidProofError:
          errorToast($t('TODO: InvalidProofError'));
          break;
        case err instanceof ProcessMessageError:
          errorToast($t('TODO: ProcessMessageError'));
          break;
        case err instanceof RetryError:
          errorToast($t('TODO: RetryError'));
          break;
        default:
          errorToast($t('TODO: UnknownError'));
          break;
      }
    } finally {
      loading = false;
    }
  }

  async function release() {
    if (!$network || !$account?.address) return;

    loading = 'releasing';

    try {
      const { msgHash, message } = bridgeTx;

      if (!msgHash || !message) {
        throw new Error('Missing msgHash or message');
      }

      // Step 1: make sure the user is on the correct chain
      await ensureCorrectChain(Number($network.id), Number(bridgeTx.srcChainId));

      // Step 2: Find out the type of bridge: ETHBridge, ERC20Bridge, etc
      const bridge = bridges[bridgeTx.tokenType];

      // Step 3: get the user's wallet
      // TODO: might not be needed to pass the chainId here
      const wallet = await getConnectedWallet(Number(bridgeTx.destChainId));

      log(`Releasing ${bridgeTx.tokenType} for transaction`, bridgeTx);

      // Step 4: Call release() method on the bridge
      const txHash = await bridge.claim({ msgHash, message, wallet });

      const { explorerUrl } = chainUrlMap[Number(bridgeTx.destChainId)];

      infoToast(
        $t('activities.actions.release.tx', {
          values: {
            token: bridgeTx.symbol,
            url: `${explorerUrl}/tx/${txHash}`,
          },
        }),
      );

      await pendingTransactions.add(txHash, $network.id);

      successToast(
        $t('activities.actions.release.success', {
          values: {
            network: $network.name,
          },
        }),
      );
    } catch (err) {
      console.error(err);

      switch (true) {
        case err instanceof NotConnectedError:
          warningToast($t('messages.account.required'));
          break;
        case err instanceof UserRejectedRequestError:
          warningToast($t('activities.actions.release_rejected'));
          break;
        case err instanceof InvalidProofError:
          errorToast($t('TODO: InvalidProofError'));
          break;
        case err instanceof ReleaseError:
          errorToast($t('TODO: ReleaseError'));
          break;
        default:
          errorToast($t('TODO: UnknownError'));
          break;
      }
    } finally {
      loading = false;
    }
  }

  onMount(async () => {
    if (bridgeTx) {
      bridgeTxStatus = bridgeTx.status; // get the current status

      // Can we start claiming/retrying/releasing?
      processable = await isBridgeTxProcessable(bridgeTx);

      try {
        polling = startPolling(bridgeTx);

        // If there is no emitter, means the bridgeTx is already DONE
        // so we do nothing here
        if (polling?.emitter) {
          // The following listeners will trigger change in the UI
          polling.emitter.on(PollingEvent.PROCESSABLE, onProcessable);
          polling.emitter.on(PollingEvent.STATUS, onStatusChange);
        }
      } catch (err) {
        console.error(err);
        // TODO: handle error
      }
    }
  });

  onDestroy(() => {
    if (polling) {
      polling.destroy();
    }
  });
</script>

<div class="Status f-items-center space-x-1">
  {#if !processable}
    <StatusDot type="pending" />
    <span>{$t('activities.status.initiated')}</span>
  {:else if loading}
    TODO: add loading indicator and text for 'claiming', 'retrying', 'releasing'
  {:else if bridgeTxStatus === MessageStatus.NEW}
    <button class="status-btn w-full" on:click={claim}>
      {$t('activities.button.claim')}
    </button>
  {:else if bridgeTxStatus === MessageStatus.RETRIABLE}
    <button class="status-btn w-full" on:click={claim}>
      {$t('activities.button.claim')}
    </button>
  {:else if bridgeTxStatus === MessageStatus.DONE}
    <StatusDot type="success" />
    <span>{$t('activities.status.claimed')}</span>
  {:else if bridgeTxStatus === MessageStatus.FAILED}
    <button class="status-btn w-full" on:click={release}>
      {$t('activities.button.claim')}
    </button>
  {:else}
    <!-- TODO: look into this possible state -->
    <StatusDot type="error" />
    <span>{$t('activities.status.error')}</span>
  {/if}
</div>
