// packages/bridge-ui/src/components/Transactions/Dialogs/ClaimDialog/ClaimSteps/ClaimPreCheck.svelte
<script lang="ts">
  import { getBalance, switchChain } from '@wagmi/core';
  import { t } from 'svelte-i18n';
  import { type Address, parseEther, zeroAddress } from 'viem';

  import { ActionButton } from '$components/Button';
  import { Icon } from '$components/Icon';
  import Spinner from '$components/Spinner/Spinner.svelte';
  import { claimConfig } from '$config';
  import type { BridgeTransaction, GetProofReceiptResponse } from '$libs/bridge';
  import { getInvocationDelayForTx } from '$libs/bridge/getInvocationDelayForTx';
  import { getChainName } from '$libs/chain';
  import { PollingEvent, type startPolling } from '$libs/polling/messageStatusPoller';
  import { config } from '$libs/wagmi';
  import { account } from '$stores/account';
  import { connectedSourceChain, switchingNetwork } from '$stores/network';

  export let tx: BridgeTransaction;
  export let polling: ReturnType<typeof startPolling>;
  export let canContinue = false;

  export let bridgeDelays: readonly bigint[];
  export let proofReceipt: GetProofReceiptResponse;

  let proofReceiptAddress: Address;

  const switchChains = async () => {
    $switchingNetwork = true;
    try {
      await switchChain(config, { chainId: Number(tx.destChainId) });
    } catch (err) {
      console.error(err);
    } finally {
      $switchingNetwork = false;
    }
  };

  export let checkingPrerequisites: boolean;

  const checkEnoughBalance = async (address: Maybe<Address>, chainId: number) => {
    if (!address) {
      return false;
    }
    checkingPrerequisites = true;

    const balance = await getBalance(config, { address, chainId });

    if (balance.value < parseEther(String(claimConfig.minimumEthToClaim))) {
      hasEnoughEth = false;
      checkingPrerequisites = false;
    }
    hasEnoughEth = true;
    checkingPrerequisites = false;
  };

  const convertSecondsToTime = (sec: number): { hours: number; minutes: number; seconds: number } => {
    let totalSeconds = Number(sec);
    const hours = Math.floor(totalSeconds / 3600);
    totalSeconds -= hours * 3600;
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;

    return { hours, minutes, seconds };
  };

  const formatTimeToString = ({
    hours,
    minutes,
    seconds,
  }: {
    hours: number;
    minutes: number;
    seconds: number;
  }): string => {
    if (hours < 0 || minutes < 0 || seconds < 0) {
      return $t('transactions.claim.steps.pre_check.no_delay');
    }

    if (hours > 0) {
      // If hours are present, include hours and minutes in the output
      return `~${hours}h ${minutes.toString().padStart(2, '0')}min`;
    } else if (minutes > 0) {
      // If no hours but minutes are present, include only minutes
      return `~${minutes}min`;
    } else if (seconds > 0) {
      // If less than a minute, show seconds
      return `~${seconds}sec`;
    }
    // If none of the above, it means no delay
    return $t('transactions.claim.steps.pre_check.no_delay');
  };

  const onDelayChange = ({ remainingDelayInSeconds }: { remainingDelayInSeconds: bigint }) => {
    if (remainingDelayInSeconds >= 0n) {
      preferredDelayInSeconds = Number(remainingDelayInSeconds);
    } else {
      preferredDelayInSeconds = 0;
    }
  };

  const checkTxDelay = async () => {
    const invocationDelaysForTx = await getInvocationDelayForTx(tx);
    preferredDelayInSeconds = Number(invocationDelaysForTx.preferredDelay);
  };

  const checkConditions = async () => {
    await checkEnoughBalance($account.address, Number(tx.destChainId));
    if (bridgeDelays && bridgeDelays[0] > 0n) {
      await checkTxDelay();
    }
  };

  $: if (proofReceipt) {
    proofReceiptAddress = proofReceipt[1];
  }

  $: txDestChainName = getChainName(Number(tx.destChainId));

  $: correctChain = Number(tx.destChainId) === $connectedSourceChain.id;

  $: if (correctChain && !checkingPrerequisites && hasEnoughEth && $account && preferredDelayInSeconds <= 0) {
    canContinue = true;
  } else {
    canContinue = false;
  }

  $: $account && tx.destChainId, checkConditions();

  $: {
    if (polling?.emitter) {
      // The following listeners will trigger change in the UI
      polling.emitter.on(PollingEvent.DELAY, onDelayChange);
    }
    remainingDelayString = formatTimeToString(convertSecondsToTime(Number(preferredDelayInSeconds)));
  }
  $: remainingDelayString = '';
  $: invocationDelayString = bridgeDelays && formatTimeToString(convertSecondsToTime(Number(bridgeDelays[0])));
  $: preferredDelayInSeconds = 0;
  $: hasEnoughEth = false;

  $: twoStepBridge = bridgeDelays && bridgeDelays[0] > 0n ? true : false;

  $: claimStep = proofReceiptAddress && proofReceiptAddress !== zeroAddress ? 2 : 1;
</script>

<div class="space-y-[25px] mt-[20px]">
  <div class="flex justify-between mb-2 items-center">
    <div class="font-bold text-primary-content">{$t('transactions.claim.steps.pre_check.title')}</div>
  </div>
  <div class="min-h-[150px] grid content-between">
    <div>
      <!-- Two step claim process -->
      {#if twoStepBridge}
        <div class="h-sep" />
        <span class="text-secondary-content">
          <!-- eslint-disable-next-line svelte/no-at-html-tags -->
          {@html $t('transactions.claim.steps.pre_check.two_step_claim.description', {
            values: { delay: invocationDelayString },
          })}
        </span>
        <div class="f-between-center mt-[20px]">
          <span class="text-secondary-content">{$t('transactions.claim.steps.pre_check.step')}</span>
          {#if checkingPrerequisites}
            <Spinner />
          {:else}
            <span>{claimStep}</span>
          {/if}
        </div>
        {#if proofReceiptAddress && proofReceiptAddress !== zeroAddress}
          <div class="f-between-center">
            <span class="text-secondary-content">{$t('transactions.claim.steps.pre_check.remaining_delay')}</span>
            {#if checkingPrerequisites}
              <Spinner />
            {:else}
              {remainingDelayString}
            {/if}
          </div>
        {/if}
        <div class="h-sep" />
      {/if}
      <div class="f-between-center">
        <span class="text-secondary-content">{$t('transactions.claim.steps.pre_check.chain_check')}</span>
        {#if checkingPrerequisites}
          <Spinner />
        {:else if correctChain}
          <Icon type="check-circle" fillClass="fill-positive-sentiment" />
        {:else}
          <Icon type="x-close-circle" fillClass="fill-negative-sentiment" />
        {/if}
      </div>
      <div class="f-between-center">
        <span class="text-secondary-content">{$t('transactions.claim.steps.pre_check.funds_check')}</span>
        {#if checkingPrerequisites}
          <Spinner />
        {:else if hasEnoughEth}
          <Icon type="check-circle" fillClass="fill-positive-sentiment" />
        {:else}
          <Icon type="x-close-circle" fillClass="fill-negative-sentiment" />
        {/if}
      </div>
    </div>
  </div>
  {#if !canContinue && !correctChain}
    <div class="h-sep" />
    <div class="f-col space-y-[16px]">
      <ActionButton
        onPopup
        priority="primary"
        disabled={$switchingNetwork}
        loading={$switchingNetwork}
        on:click={() => {
          switchChains();
        }}>{$t('common.switch_to')} {txDestChainName}</ActionButton>
    </div>
  {/if}
</div>

// packages/bridge-ui-next/src/components/Dialogs/Shared/ClaimPreCheck.tsx
"use client";

import { getBalance, switchChain } from "@wagmi/core";
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useState,
} from "react";
import { type Address, getAddress, parseEther } from "viem";

import Alert from "@/components/Alert/Alert";
import { ActionButton } from "@/components/Button";
import { Icon } from "@/components/Icon";
import Spinner from "@/components/Spinner/Spinner";
import { Tooltip } from "@/components/Tooltip";
import { claimConfig } from "$config";
import { useTranslation } from "@/i18n/useTranslation";
import { type BridgeTransaction } from "@/libs/bridge";
import { getChainName } from "@/libs/chain";
import { shortenAddress } from "@/libs/util/shortenAddress";
import { config } from "@/libs/wagmi";
import { useAccount } from "@/stores/account";
import {
  switchingNetwork,
  useConnectedSourceChain,
  useSwitchingNetwork,
} from "@/stores/network";

export interface ClaimPreCheckProps {
  tx: BridgeTransaction;
  /** Two-way bound in the original (`bind:canContinue`). */
  canContinue?: boolean;
  onCanContinueChange?: (value: boolean) => void;
  /** Two-way bound in the original (`bind:hideContinueButton`). */
  hideContinueButton?: boolean;
  onHideContinueButtonChange?: (value: boolean) => void;
  /** Svelte `dispatch('closeDialog')` -> callback prop. */
  onCloseDialog?: () => void;
}

/** Imperative handle mirroring Svelte's `export const closeDialog`. */
export interface ClaimPreCheckHandle {
  closeDialog: () => void;
}

const ClaimPreCheck = forwardRef<ClaimPreCheckHandle, ClaimPreCheckProps>(
  function ClaimPreCheck(
    {
      tx,
      canContinue = false,
      onCanContinueChange,
      hideContinueButton = false,
      onHideContinueButtonChange,
      onCloseDialog,
    },
    ref,
  ) {
    const { t } = useTranslation();

    // `$account` reactive subscription (the watcher writes the vanilla store).
    const account = useAccount((state) => state);
    // `$connectedSourceChain` / `$switchingNetwork` reactive subscriptions.
    const connectedSourceChainValue = useConnectedSourceChain();
    const switchingNetworkValue = useSwitchingNetwork();

    // let checkingPrerequisites: boolean;
    const [checkingPrerequisites, setCheckingPrerequisites] =
      useState<boolean>(false);
    // $: hasEnoughEth = false; (also set inside checkConditions)
    const [hasEnoughEth, setHasEnoughEth] = useState(false);

    const closeDialog = useCallback(() => {
      onCloseDialog?.();
    }, [onCloseDialog]);

    useImperativeHandle(ref, () => ({ closeDialog }), [closeDialog]);

    const switchChains = async () => {
      switchingNetwork.setState(true);
      try {
        await switchChain(config, { chainId: Number(tx.destChainId) });
      } catch (err) {
        console.error(err);
      } finally {
        switchingNetwork.setState(false);
      }
    };

    const checkEnoughBalance = useCallback(
      async (address: Maybe<Address>, chainId: number) => {
        if (!address) {
          return false;
        }

        const balance = await getBalance(config, { address, chainId });

        if (
          balance.value >= parseEther(String(claimConfig.minimumEthToClaim))
        ) {
          return true;
        }
        return false;
      },
      [],
    );

    const checkConditions = useCallback(async () => {
      setCheckingPrerequisites(true);

      const results = await Promise.allSettled([
        checkEnoughBalance(account?.address, Number(tx.destChainId)),
      ]);

      results.forEach((result, index) => {
        if (result.status === "fulfilled") {
          if (index === 0) {
            setHasEnoughEth(result.value);
          }
        } else {
          // You can log or handle errors here if a promise was rejected.
          console.error(`Error in promise at index ${index}:`, result.reason);
        }
      });
      setCheckingPrerequisites(false);
    }, [account?.address, checkEnoughBalance, tx.destChainId]);

    // $: txDestChainName = getChainName(Number(tx.destChainId));
    const txDestChainName = useMemo(
      () => getChainName(Number(tx.destChainId)),
      [tx.destChainId],
    );

    // $: correctChain = Number(tx.destChainId) === $connectedSourceChain?.id;
    const correctChain =
      Number(tx.destChainId) === connectedSourceChainValue?.id;

    // $: hasPaidProcessingFee = tx.processingFee > 0;
    const hasPaidProcessingFee = tx.processingFee > 0;

    // $: onlyDestOwnerCanClaimWarning = false; + $: if (...) {...}
    const onlyDestOwnerCanClaimWarning = useMemo(() => {
      if (tx.message?.to && account?.address && tx.message.destOwner) {
        const destOwnerMustClaim = tx.message.gasLimit === 0; // If gasLimit is 0, the destOwner must claim
        const isDestOwner =
          getAddress(account.address) === getAddress(tx.message.destOwner);

        if (destOwnerMustClaim && !isDestOwner) {
          return true;
        }
        return false;
      }
      return false;
    }, [
      tx.message?.to,
      tx.message?.destOwner,
      tx.message?.gasLimit,
      account?.address,
    ]);

    // $: successfulPreChecks = correctChain && hasEnoughEth;
    const successfulPreChecks = correctChain && hasEnoughEth;

    // $: if (!checkingPrerequisites && successfulPreChecks && $account && !onlyDestOwnerCanClaimWarning) {
    //      hideContinueButton = false; canContinue = true;
    //    } else { if (!correctChain) hideContinueButton = true; canContinue = false; }
    useEffect(() => {
      if (
        !checkingPrerequisites &&
        successfulPreChecks &&
        account &&
        !onlyDestOwnerCanClaimWarning
      ) {
        if (hideContinueButton !== false) onHideContinueButtonChange?.(false);
        if (canContinue !== true) onCanContinueChange?.(true);
      } else {
        if (!correctChain) {
          if (hideContinueButton !== true) onHideContinueButtonChange?.(true);
        }
        if (canContinue !== false) onCanContinueChange?.(false);
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [
      checkingPrerequisites,
      successfulPreChecks,
      account,
      onlyDestOwnerCanClaimWarning,
      correctChain,
    ]);

    // $: $account && checkConditions();
    useEffect(() => {
      if (account) {
        checkConditions();
      }
    }, [account, checkConditions]);

    // onMount(() => { checkConditions(); });
    useEffect(() => {
      checkConditions();
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    return (
      <div className="space-y-[25px] mt-[20px]">
        <div className="flex justify-between mb-2 items-center">
          <div className="font-bold text-primary-content">
            {t("transactions.claim.steps.pre_check.title")}
          </div>
        </div>
        <div className="min-h-[150px] grid content-between">
          {onlyDestOwnerCanClaimWarning ? (
            <div className="f-between-center">
              <div className="f-row gap-1">
                <div className="f-col">
                  <Alert type="info">
                    {t(
                      "transactions.claim.steps.pre_check.only_destowner_can_claim",
                    )}
                    <div className="h-sep" />
                    <span className="font-bold">
                      {t("common.owner.destination")}:{" "}
                    </span>
                    {shortenAddress(tx.message?.destOwner, 6, 4)}
                  </Alert>
                </div>
              </div>
              {checkingPrerequisites ? <Spinner /> : null}
            </div>
          ) : (
            <div>
              <div className="f-between-center">
                <div className="f-row gap-1">
                  <span className="text-secondary-content">
                    {t("transactions.claim.steps.pre_check.chain_check")}
                  </span>
                  <Tooltip>
                    <h2>
                      {t(
                        "transactions.claim.steps.pre_check.tooltip.chain.title",
                      )}
                    </h2>

                    <span>
                      {t(
                        "transactions.claim.steps.pre_check.tooltip.chain.description",
                      )}
                    </span>
                  </Tooltip>
                </div>
                {checkingPrerequisites ? (
                  <Spinner />
                ) : correctChain ? (
                  <Icon
                    type="check-circle"
                    fillClass="fill-positive-sentiment"
                  />
                ) : (
                  <Icon
                    type="x-close-circle"
                    fillClass="fill-negative-sentiment"
                  />
                )}
              </div>
              <div className="f-between-center">
                <div className="f-row gap-1">
                  <span className="text-secondary-content">
                    {t("transactions.claim.steps.pre_check.funds_check")}
                  </span>
                  <Tooltip>
                    <h2>
                      {t(
                        "transactions.claim.steps.pre_check.tooltip.funds.title",
                      )}
                    </h2>
                    <span>
                      {t(
                        "transactions.claim.steps.pre_check.tooltip.funds.description",
                      )}{" "}
                    </span>
                  </Tooltip>
                </div>
                {checkingPrerequisites ? (
                  <Spinner />
                ) : hasEnoughEth ? (
                  <Icon
                    type="check-circle"
                    fillClass="fill-positive-sentiment"
                  />
                ) : (
                  <Icon
                    type="x-close-circle"
                    fillClass="fill-negative-sentiment"
                  />
                )}
              </div>
              {hasPaidProcessingFee ? (
                <>
                  <div className="h-sep" />
                  <div className="f-between-center">
                    {checkingPrerequisites ? (
                      <Spinner />
                    ) : (
                      <Alert type="info">
                        {t(
                          "transactions.claim.steps.pre_check.tooltip.processing_fee.description",
                        )}
                      </Alert>
                    )}
                  </div>
                </>
              ) : null}
            </div>
          )}
        </div>
        {!canContinue && !correctChain && !onlyDestOwnerCanClaimWarning ? (
          <>
            <div className="h-sep" />
            <div className="f-col space-y-[16px]">
              <ActionButton
                onPopup
                priority="primary"
                disabled={switchingNetworkValue}
                loading={switchingNetworkValue}
                onClick={() => {
                  switchChains();
                }}
              >
                {t("common.switch_to")} {txDestChainName}
              </ActionButton>
            </div>
          </>
        ) : !canContinue ? (
          <>
            <div className="h-sep" />
            <div className="f-col space-y-[16px]">
              <ActionButton
                onPopup
                priority="primary"
                onClick={() => {
                  closeDialog();
                }}
              >
                {t("common.ok")}
              </ActionButton>
            </div>
          </>
        ) : null}
      </div>
    );
  },
);

export default ClaimPreCheck;
