// packages/bridge-ui/src/components/Transactions/Dialogs/ClaimDialog/ClaimSteps/ClaimConfirmStep.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { t } from 'svelte-i18n';
  import type { Hash } from 'viem';

  import { chainConfig } from '$chainConfig';
  import ActionButton from '$components/Button/ActionButton.svelte';
  import { Icon, type IconType } from '$components/Icon';
  import { Spinner } from '$components/Spinner';
  import type { BridgeTransaction } from '$libs/bridge';
  import { theme } from '$stores/theme';

  import { TWO_STEP_STATE } from '../types';

  export let canClaim = false;

  export let claimingDone = false;

  export let claiming = false;

  export let proveOrClaimStep: TWO_STEP_STATE | null;

  export let bridgeTx: BridgeTransaction;

  export let txHash: Hash;

  const dispatch = createEventDispatcher();

  const handleClaimClick = async () => {
    dispatch('claim');
  };

  const getSuccessTitle = () => {
    if (proveOrClaimStep === TWO_STEP_STATE.PROVE) {
      return $t('bridge.step.confirm.success.prove');
    }

    return $t('bridge.step.confirm.success.claim');
  };

  const getSuccessDescription = () => {
    if (!txHash) return;
    if (proveOrClaimStep === TWO_STEP_STATE.PROVE) {
      return $t('bridge.step.confirm.success.prove_description');
    }
    const explorer = chainConfig[Number(bridgeTx.destChainId)]?.blockExplorers?.default.url;
    const url = `${explorer}/tx/${txHash}`;

    successDescription = $t('transactions.actions.claim.success.message', { values: { url } });
  };

  $: if (txHash && claimingDone) {
    getSuccessDescription();
  }

  $: claimOrProveActionButton =
    proveOrClaimStep === TWO_STEP_STATE.CLAIM
      ? $t('transactions.claim.steps.confirm.claim_button')
      : $t('transactions.claim.steps.confirm.prove');

  $: proceedText =
    proveOrClaimStep === TWO_STEP_STATE.CLAIM
      ? $t('transactions.claim.steps.confirm.proceed')
      : $t('transactions.claim.steps.confirm.prove');

  $: proceedDescription =
    proveOrClaimStep === TWO_STEP_STATE.CLAIM
      ? $t('transactions.claim.steps.confirm.claim_description')
      : $t('transactions.claim.steps.confirm.prove_description');

  $: bridgeIcon = `bridge-${$theme}` as IconType;
  $: successIcon = `success-${$theme}` as IconType;

  $: statusTitle = getSuccessTitle();
  let successDescription = '';

  $: claimDisabled = !canClaim || claiming;
</script>

<div class="space-y-[18px]">
  <div class="mt-[30px]">
    <section id="txStatus">
      <div class="flex flex-col justify-content-center items-center">
        {#if claimingDone}
          <Icon type={successIcon} size={160} />
          <div id="text" class="f-col my-[30px] text-center">
            <!-- eslint-disable-next-line svelte/no-at-html-tags -->
            <h1>{@html statusTitle}</h1>
            <!-- eslint-disable-next-line svelte/no-at-html-tags -->
            <span class="">{@html successDescription}</span>
          </div>
        {:else if claiming}
          <Spinner class="!w-[160px] !h-[160px] text-primary-brand" />
          <div id="text" class="f-col my-[30px] text-center">
            <h1 class="mb-[16px]">{$t('bridge.step.confirm.processing')}</h1>
            <span>{$t('bridge.step.confirm.approve.pending')}</span>
          </div>
        {:else if !claiming && !claimingDone}
          <Icon type={bridgeIcon} size={160} />
          <div id="text" class="f-col my-[30px] text-center">
            <h1 class="mb-[16px]">{proceedText}</h1>
            <span>{proceedDescription}</span>
          </div>
        {/if}
      </div>
    </section>
    {#if !claimingDone}
      <section id="actions" class="f-col w-full">
        <div class="h-sep mb-[30px]" />
        <ActionButton
          onPopup
          priority="primary"
          loading={claiming}
          on:click={() => handleClaimClick()}
          disabled={claimDisabled}>{claimOrProveActionButton}</ActionButton>
      </section>
    {/if}
  </div>
</div>

// packages/bridge-ui-next/src/components/Dialogs/Shared/ClaimConfirmStep.tsx
"use client";

import { useMemo } from "react";
import type { Hash } from "viem";

import ActionButton from "@/components/Button/ActionButton";
import { Icon, type IconType } from "@/components/Icon";
import { Spinner } from "@/components/Spinner";
import { chainConfig } from "@/config/generated/chainConfig";
import { useTranslation } from "@/i18n/useTranslation";
import type { BridgeTransaction } from "@/libs/bridge";
import { useThemeStore } from "@/stores/useThemeStore";

export interface ClaimConfirmStepProps {
  canClaim?: boolean;
  claimingDone?: boolean;
  claiming?: boolean;
  bridgeTx: BridgeTransaction;
  txHash: Hash;
  // canForceTransaction?: boolean;
  /** Svelte `dispatch('claim')` -> callback prop. */
  onClaim?: () => void;
  // onForceClaim?: () => void;
}

export default function ClaimConfirmStep({
  canClaim = false,
  claimingDone = false,
  claiming = false,
  bridgeTx,
  txHash,
  onClaim,
}: ClaimConfirmStepProps) {
  const { t } = useTranslation();
  const theme = useThemeStore((state) => state.theme);

  const handleClaimClick = async () => {
    onClaim?.();
  };

  // const handleForceClaim = async () => {
  //   onForceClaim?.();
  // };

  // const getSuccessTitle = () => $t('bridge.step.confirm.success.claim');
  // $: statusTitle = getSuccessTitle();
  const statusTitle = t("bridge.step.confirm.success.claim");

  // $: if (txHash && claimingDone) { getSuccessDescription(); }
  // let successDescription = '';
  const successDescription = useMemo(() => {
    if (!(txHash && claimingDone)) return "";
    if (!txHash) return "";

    const explorer =
      chainConfig[Number(bridgeTx.destChainId)]?.blockExplorers?.default.url;
    const url = `${explorer}/tx/${txHash}`;

    return t("transactions.actions.claim.success.message", { url });
  }, [txHash, claimingDone, bridgeTx.destChainId, t]);

  // $: bridgeIcon = `bridge-${$theme}` as IconType;
  const bridgeIcon = `bridge-${theme}` as IconType;
  // $: successIcon = `success-${$theme}` as IconType;
  const successIcon = `success-${theme}` as IconType;

  // $: claimDisabled = !canClaim || claiming;
  const claimDisabled = !canClaim || claiming;

  return (
    <div className="space-y-[18px]">
      <div className="mt-[30px]">
        <section id="txStatus">
          <div className="flex flex-col justify-content-center items-center">
            {claimingDone ? (
              <>
                <Icon type={successIcon} size={160} />
                <div id="text" className="f-col my-[30px] text-center">
                  <h1 dangerouslySetInnerHTML={{ __html: statusTitle }} />
                  <span
                    className=""
                    dangerouslySetInnerHTML={{ __html: successDescription }}
                  />
                </div>
              </>
            ) : claiming ? (
              <>
                <Spinner className="!w-[160px] !h-[160px] text-primary-brand" />
                <div id="text" className="f-col my-[30px] text-center">
                  <h1 className="mb-[16px]">
                    {t("bridge.step.confirm.processing")}
                  </h1>
                  <span>{t("bridge.step.confirm.approve.pending")}</span>
                </div>
              </>
            ) : !claiming && !claimingDone ? (
              <>
                <Icon type={bridgeIcon} size={160} />
                <div id="text" className="f-col my-[30px] text-center">
                  <h1 className="mb-[16px]">
                    {t("transactions.claim.steps.confirm.proceed")}
                  </h1>
                  <span>
                    {t("transactions.claim.steps.confirm.claim_description")}
                  </span>
                </div>
              </>
            ) : null}
          </div>
        </section>
        {!claimingDone ? (
          <section id="actions" className="f-col w-full gap-2">
            <div className="h-sep mb-[30px]" />
            <ActionButton
              onPopup
              priority="primary"
              loading={claiming}
              onClick={() => handleClaimClick()}
              disabled={claimDisabled}
            >
              {t("transactions.claim.steps.confirm.claim_button")}
            </ActionButton>
            {/* {canForceTransaction ? (
              <ActionButton
                onPopup
                priority="primary"
                loading={claiming}
                onClick={() => handleForceClaim()}
                disabled={claimDisabled}>
                Force transaction
              </ActionButton>
            ) : null} */}
          </section>
        ) : null}
      </div>
    </div>
  );
}
